// =============================================================================
// BASE CONTENT GENERATION LIBRARY
// Deterministic content generation for 4,600+ pages
// Day 1: Core game data (TOWN_HALL_DATA + BUILDER_HALL_DATA)
// =============================================================================

// -----------------------------------------------------------------------------
// TOWN HALL DATA (TH3 - TH18)
// Real Clash of Clans buildings, troops, heroes, and spells per level
// -----------------------------------------------------------------------------
const TOWN_HALL_DATA = {
  3: {
    name: 'Town Hall 3',
    maxLevel: 3,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin'],
    newBuildings: ['Mortar', '2nd Cannon', '2nd Archer Tower'],
    heroesAvailable: [],
    spellsAvailable: [],
    armyCampSpace: 70,
    wallCount: 50,
    trapCount: 2,
    description: 'an early-game level where players learn the fundamentals of base building and troop deployment',
    tier: 'beginner',
  },
  4: {
    name: 'Town Hall 4',
    maxLevel: 4,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon'],
    newBuildings: ['Air Defense', '2nd Mortar', 'additional Cannon and Archer Tower'],
    heroesAvailable: [],
    spellsAvailable: [],
    armyCampSpace: 80,
    wallCount: 75,
    trapCount: 4,
    description: 'the first level where air attacks become a factor thanks to the introduction of the Air Defense',
    tier: 'beginner',
  },
  5: {
    name: 'Town Hall 5',
    maxLevel: 5,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard'],
    newBuildings: ['Wizard Tower', 'Spell Factory', '3rd Cannon', '3rd Archer Tower'],
    heroesAvailable: [],
    spellsAvailable: ['Lightning Spell'],
    armyCampSpace: 135,
    wallCount: 100,
    trapCount: 6,
    description: 'a key milestone where the Wizard Tower and Spell Factory unlock, adding splash damage defense and offensive spell support',
    tier: 'beginner',
  },
  6: {
    name: 'Town Hall 6',
    maxLevel: 6,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer'],
    newBuildings: ['Air Sweeper', '2nd Air Defense', '2nd Wizard Tower'],
    heroesAvailable: [],
    spellsAvailable: ['Lightning Spell', 'Healing Spell'],
    armyCampSpace: 150,
    wallCount: 125,
    trapCount: 6,
    description: 'an important defensive upgrade with the Air Sweeper that pushes back air units and a second Air Defense',
    tier: 'beginner',
  },
  7: {
    name: 'Town Hall 7',
    maxLevel: 7,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'Hog Rider', 'Minion'],
    newBuildings: ['Hidden Tesla', 'Dark Elixir Drill', 'Dark Elixir Storage', 'Dark Barracks'],
    heroesAvailable: ['Barbarian King'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell'],
    armyCampSpace: 200,
    wallCount: 175,
    trapCount: 8,
    description: 'a game-changing level that introduces the Barbarian King hero, Dark Elixir economy, Dragons for powerful air attacks, and the Hidden Tesla defense',
    tier: 'intermediate',
  },
  8: {
    name: 'Town Hall 8',
    maxLevel: 8,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla', 'Bomb Tower'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'PEKKA', 'Hog Rider', 'Minion', 'Valkyrie', 'Golem'],
    newBuildings: ['Bomb Tower', 'Dark Spell Factory', '3rd Air Defense', '2nd Hidden Tesla'],
    heroesAvailable: ['Barbarian King'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell', 'Poison Spell', 'Earthquake Spell'],
    armyCampSpace: 200,
    wallCount: 225,
    trapCount: 10,
    description: 'a crucial competitive level where GoWiPe and Hog Rider attacks dominate, with the Dark Spell Factory adding Poison and Earthquake Spells',
    tier: 'intermediate',
  },
  9: {
    name: 'Town Hall 9',
    maxLevel: 9,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla', 'Bomb Tower', 'X-Bow'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'PEKKA', 'Hog Rider', 'Minion', 'Valkyrie', 'Golem', 'Witch', 'Lava Hound', 'Baby Dragon'],
    newBuildings: ['X-Bow (x2)', '4th Air Defense', '2nd Air Sweeper', 'additional Wizard Tower'],
    heroesAvailable: ['Barbarian King', 'Archer Queen'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell', 'Jump Spell', 'Freeze Spell', 'Poison Spell', 'Earthquake Spell', 'Haste Spell'],
    armyCampSpace: 220,
    wallCount: 250,
    trapCount: 12,
    description: 'widely considered the most strategic Town Hall level, introducing the Archer Queen hero, X-Bows, and classic attack strategies like GoHo and LavaLoon',
    tier: 'intermediate',
  },
  10: {
    name: 'Town Hall 10',
    maxLevel: 10,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla', 'Bomb Tower', 'X-Bow', 'Inferno Tower'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'PEKKA', 'Hog Rider', 'Minion', 'Valkyrie', 'Golem', 'Witch', 'Lava Hound', 'Baby Dragon', 'Bowler', 'Miner'],
    newBuildings: ['Inferno Tower (x2)', '3rd X-Bow', 'Bomb Tower', 'additional Cannon and Archer Tower'],
    heroesAvailable: ['Barbarian King', 'Archer Queen'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell', 'Jump Spell', 'Freeze Spell', 'Clone Spell', 'Poison Spell', 'Earthquake Spell', 'Haste Spell', 'Bat Spell'],
    armyCampSpace: 240,
    wallCount: 275,
    trapCount: 14,
    description: 'a major power spike with the devastating Inferno Towers that melt high-HP troops, alongside Bowlers and Miners for versatile attack strategies',
    tier: 'advanced',
  },
  11: {
    name: 'Town Hall 11',
    maxLevel: 11,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla', 'Bomb Tower', 'X-Bow', 'Inferno Tower', 'Eagle Artillery'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'PEKKA', 'Hog Rider', 'Minion', 'Valkyrie', 'Golem', 'Witch', 'Lava Hound', 'Baby Dragon', 'Bowler', 'Miner', 'Electro Dragon', 'Ice Golem'],
    newBuildings: ['Eagle Artillery', '4th X-Bow', '3rd Inferno Tower', 'additional Wizard Tower and Archer Tower'],
    heroesAvailable: ['Barbarian King', 'Archer Queen', 'Grand Warden'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell', 'Jump Spell', 'Freeze Spell', 'Clone Spell', 'Invisibility Spell', 'Poison Spell', 'Earthquake Spell', 'Haste Spell', 'Bat Spell'],
    armyCampSpace: 260,
    wallCount: 300,
    trapCount: 15,
    description: 'a massive leap with the Eagle Artillery providing map-wide splash damage, the Grand Warden hero with his life-saving ability, and powerful Electro Dragons',
    tier: 'advanced',
  },
  12: {
    name: 'Town Hall 12',
    maxLevel: 12,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla', 'Bomb Tower', 'X-Bow', 'Inferno Tower', 'Eagle Artillery', 'Giga Tesla'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'PEKKA', 'Hog Rider', 'Minion', 'Valkyrie', 'Golem', 'Witch', 'Lava Hound', 'Baby Dragon', 'Bowler', 'Miner', 'Electro Dragon', 'Ice Golem', 'Yeti', 'Headhunter'],
    newBuildings: ['Giga Tesla (on Town Hall)', 'Siege Workshop', 'additional Tesla and Bomb Tower'],
    heroesAvailable: ['Barbarian King', 'Archer Queen', 'Grand Warden'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell', 'Jump Spell', 'Freeze Spell', 'Clone Spell', 'Invisibility Spell', 'Poison Spell', 'Earthquake Spell', 'Haste Spell', 'Bat Spell'],
    siegeMachines: ['Wall Wrecker', 'Battle Blimp', 'Stone Slammer', 'Siege Barracks', 'Log Launcher'],
    armyCampSpace: 280,
    wallCount: 300,
    trapCount: 16,
    description: 'an end-game milestone featuring the Giga Tesla built into the Town Hall, the Siege Workshop for powerful siege machines like Wall Wrecker and Battle Blimp, plus Yeti and Headhunter troops',
    tier: 'advanced',
  },
  13: {
    name: 'Town Hall 13',
    maxLevel: 13,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla', 'Bomb Tower', 'X-Bow', 'Inferno Tower', 'Eagle Artillery', 'Giga Inferno', 'Scattershot'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'PEKKA', 'Hog Rider', 'Minion', 'Valkyrie', 'Golem', 'Witch', 'Lava Hound', 'Baby Dragon', 'Bowler', 'Miner', 'Electro Dragon', 'Ice Golem', 'Yeti', 'Headhunter', 'Super Troops'],
    newBuildings: ['Giga Inferno (replaces Giga Tesla)', 'Scattershot (x2)', 'Royal Champion Altar'],
    heroesAvailable: ['Barbarian King', 'Archer Queen', 'Grand Warden', 'Royal Champion'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell', 'Jump Spell', 'Freeze Spell', 'Clone Spell', 'Invisibility Spell', 'Poison Spell', 'Earthquake Spell', 'Haste Spell', 'Bat Spell'],
    siegeMachines: ['Wall Wrecker', 'Battle Blimp', 'Stone Slammer', 'Siege Barracks', 'Log Launcher', 'Flame Flinger'],
    armyCampSpace: 300,
    wallCount: 300,
    trapCount: 17,
    description: 'a pivotal level introducing the Royal Champion as the fourth hero, the Giga Inferno upgrade for the Town Hall, devastating Scattershots, and the ability to unlock Super Troops',
    tier: 'endgame',
  },
  14: {
    name: 'Town Hall 14',
    maxLevel: 14,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla', 'Bomb Tower', 'X-Bow', 'Inferno Tower', 'Eagle Artillery', 'Giga Inferno', 'Scattershot'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'PEKKA', 'Hog Rider', 'Minion', 'Valkyrie', 'Golem', 'Witch', 'Lava Hound', 'Baby Dragon', 'Bowler', 'Miner', 'Electro Dragon', 'Ice Golem', 'Yeti', 'Headhunter', 'Dragon Rider', 'Super Troops'],
    newBuildings: ['Pet House', 'additional Inferno Tower and X-Bow upgrades'],
    heroesAvailable: ['Barbarian King', 'Archer Queen', 'Grand Warden', 'Royal Champion'],
    pets: ['L.A.S.S.I', 'Electro Owl', 'Mighty Yak', 'Unicorn'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell', 'Jump Spell', 'Freeze Spell', 'Clone Spell', 'Invisibility Spell', 'Poison Spell', 'Earthquake Spell', 'Haste Spell', 'Bat Spell'],
    siegeMachines: ['Wall Wrecker', 'Battle Blimp', 'Stone Slammer', 'Siege Barracks', 'Log Launcher', 'Flame Flinger'],
    armyCampSpace: 300,
    wallCount: 300,
    trapCount: 18,
    description: 'a transformative level that introduces Hero Pets including L.A.S.S.I, Electro Owl, Mighty Yak, and Unicorn, which pair with heroes to dramatically increase their effectiveness',
    tier: 'endgame',
  },
  15: {
    name: 'Town Hall 15',
    maxLevel: 15,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla', 'Bomb Tower', 'X-Bow', 'Inferno Tower', 'Eagle Artillery', 'Giga Inferno', 'Scattershot', 'Monolith', 'Spell Tower'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'PEKKA', 'Hog Rider', 'Minion', 'Valkyrie', 'Golem', 'Witch', 'Lava Hound', 'Baby Dragon', 'Bowler', 'Miner', 'Electro Dragon', 'Ice Golem', 'Yeti', 'Headhunter', 'Dragon Rider', 'Electro Titan', 'Super Troops'],
    newBuildings: ['Monolith', 'Spell Tower (x2)', '3rd Scattershot', 'additional traps'],
    heroesAvailable: ['Barbarian King', 'Archer Queen', 'Grand Warden', 'Royal Champion'],
    pets: ['L.A.S.S.I', 'Electro Owl', 'Mighty Yak', 'Unicorn', 'Frosty', 'Diggy', 'Poison Lizard', 'Phoenix'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell', 'Jump Spell', 'Freeze Spell', 'Clone Spell', 'Invisibility Spell', 'Recall Spell', 'Poison Spell', 'Earthquake Spell', 'Haste Spell', 'Bat Spell'],
    siegeMachines: ['Wall Wrecker', 'Battle Blimp', 'Stone Slammer', 'Siege Barracks', 'Log Launcher', 'Flame Flinger', 'Battle Drill'],
    armyCampSpace: 320,
    wallCount: 325,
    trapCount: 20,
    description: 'a massive content update featuring the Monolith that deals percentage-based damage, Spell Towers that cast spells automatically, the Recall Spell for repositioning troops, and four new Hero Pets including the powerful Phoenix',
    tier: 'endgame',
  },
  16: {
    name: 'Town Hall 16',
    maxLevel: 16,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla', 'Bomb Tower', 'X-Bow', 'Inferno Tower', 'Eagle Artillery', 'Giga Inferno', 'Scattershot', 'Monolith', 'Spell Tower', 'Multi-Archer Tower', 'Ricochet Cannon'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'PEKKA', 'Hog Rider', 'Minion', 'Valkyrie', 'Golem', 'Witch', 'Lava Hound', 'Baby Dragon', 'Bowler', 'Miner', 'Electro Dragon', 'Ice Golem', 'Yeti', 'Headhunter', 'Dragon Rider', 'Electro Titan', 'Root Rider', 'Super Troops'],
    newBuildings: ['Multi-Archer Tower', 'Ricochet Cannon', 'Merged Defense buildings'],
    heroesAvailable: ['Barbarian King', 'Archer Queen', 'Grand Warden', 'Royal Champion'],
    pets: ['L.A.S.S.I', 'Electro Owl', 'Mighty Yak', 'Unicorn', 'Frosty', 'Diggy', 'Poison Lizard', 'Phoenix', 'Spirit Fox'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell', 'Jump Spell', 'Freeze Spell', 'Clone Spell', 'Invisibility Spell', 'Recall Spell', 'Overgrowth Spell', 'Poison Spell', 'Earthquake Spell', 'Haste Spell', 'Bat Spell'],
    siegeMachines: ['Wall Wrecker', 'Battle Blimp', 'Stone Slammer', 'Siege Barracks', 'Log Launcher', 'Flame Flinger', 'Battle Drill'],
    armyCampSpace: 320,
    wallCount: 325,
    trapCount: 21,
    description: 'the Merged Defense era introducing the Multi-Archer Tower and Ricochet Cannon, the devastating Root Rider troop, Spirit Fox pet, and the ability to merge certain defense buildings for increased power',
    tier: 'endgame',
  },
  17: {
    name: 'Town Hall 17',
    maxLevel: 17,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla', 'Bomb Tower', 'X-Bow', 'Inferno Tower', 'Eagle Artillery', 'Giga Inferno', 'Scattershot', 'Monolith', 'Spell Tower', 'Multi-Archer Tower', 'Ricochet Cannon', 'Merged Mortar', 'Zap Trap'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'PEKKA', 'Hog Rider', 'Minion', 'Valkyrie', 'Golem', 'Witch', 'Lava Hound', 'Baby Dragon', 'Bowler', 'Miner', 'Electro Dragon', 'Ice Golem', 'Yeti', 'Headhunter', 'Dragon Rider', 'Electro Titan', 'Root Rider', 'Super Troops'],
    newBuildings: ['Merged Mortar', 'Zap Trap', 'Apprentice Warden Altar'],
    heroesAvailable: ['Barbarian King', 'Archer Queen', 'Grand Warden', 'Royal Champion', 'Apprentice Warden'],
    pets: ['L.A.S.S.I', 'Electro Owl', 'Mighty Yak', 'Unicorn', 'Frosty', 'Diggy', 'Poison Lizard', 'Phoenix', 'Spirit Fox', 'Angry Jelly'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell', 'Jump Spell', 'Freeze Spell', 'Clone Spell', 'Invisibility Spell', 'Recall Spell', 'Overgrowth Spell', 'Poison Spell', 'Earthquake Spell', 'Haste Spell', 'Bat Spell'],
    siegeMachines: ['Wall Wrecker', 'Battle Blimp', 'Stone Slammer', 'Siege Barracks', 'Log Launcher', 'Flame Flinger', 'Battle Drill'],
    armyCampSpace: 330,
    wallCount: 325,
    trapCount: 22,
    description: 'a landmark update introducing the Apprentice Warden as the fifth hero, the Merged Mortar for concentrated splash damage, the Zap Trap for stunning attackers, and the Angry Jelly pet',
    tier: 'endgame',
  },
  18: {
    name: 'Town Hall 18',
    maxLevel: 18,
    keyDefenses: ['Cannon', 'Archer Tower', 'Mortar', 'Air Defense', 'Wizard Tower', 'Air Sweeper', 'Hidden Tesla', 'Bomb Tower', 'X-Bow', 'Inferno Tower', 'Eagle Artillery', 'Giga Inferno', 'Scattershot', 'Monolith', 'Spell Tower', 'Multi-Archer Tower', 'Ricochet Cannon', 'Merged Mortar', 'Zap Trap', 'Merged Wizard Tower', 'Reflector'],
    keyTroops: ['Barbarian', 'Archer', 'Giant', 'Goblin', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'PEKKA', 'Hog Rider', 'Minion', 'Valkyrie', 'Golem', 'Witch', 'Lava Hound', 'Baby Dragon', 'Bowler', 'Miner', 'Electro Dragon', 'Ice Golem', 'Yeti', 'Headhunter', 'Dragon Rider', 'Electro Titan', 'Root Rider', 'Druid', 'Super Troops'],
    newBuildings: ['Merged Wizard Tower', 'Reflector', 'additional defense upgrades'],
    heroesAvailable: ['Barbarian King', 'Archer Queen', 'Grand Warden', 'Royal Champion', 'Apprentice Warden'],
    pets: ['L.A.S.S.I', 'Electro Owl', 'Mighty Yak', 'Unicorn', 'Frosty', 'Diggy', 'Poison Lizard', 'Phoenix', 'Spirit Fox', 'Angry Jelly'],
    spellsAvailable: ['Lightning Spell', 'Healing Spell', 'Rage Spell', 'Jump Spell', 'Freeze Spell', 'Clone Spell', 'Invisibility Spell', 'Recall Spell', 'Overgrowth Spell', 'Poison Spell', 'Earthquake Spell', 'Haste Spell', 'Bat Spell'],
    siegeMachines: ['Wall Wrecker', 'Battle Blimp', 'Stone Slammer', 'Siege Barracks', 'Log Launcher', 'Flame Flinger', 'Battle Drill'],
    armyCampSpace: 340,
    wallCount: 325,
    trapCount: 23,
    description: 'the current maximum Town Hall level featuring the Merged Wizard Tower for devastating splash damage, the Reflector defense that bounces projectiles, and the Druid troop with healing and rage aura abilities',
    tier: 'endgame',
  },
};

// -----------------------------------------------------------------------------
// BUILDER HALL DATA (BH3 - BH10)
// Real Clash of Clans Builder Base buildings, troops, and abilities
// -----------------------------------------------------------------------------
const BUILDER_HALL_DATA = {
  3: {
    name: 'Builder Hall 3',
    maxLevel: 3,
    keyDefenses: ['Cannon', 'Archer Tower', 'Double Cannon', 'Crusher', 'Firecracker'],
    keyTroops: ['Raged Barbarian', 'Sneaky Archer', 'Boxer Giant'],
    newBuildings: ['Crusher', 'Gem Mine', '2nd Army Camp'],
    heroesAvailable: [],
    starLaboratory: true,
    description: 'an introductory Builder Base level where the Crusher provides devastating melee damage against ground troops and players learn versus battle mechanics',
    tier: 'beginner',
  },
  4: {
    name: 'Builder Hall 4',
    maxLevel: 4,
    keyDefenses: ['Cannon', 'Archer Tower', 'Double Cannon', 'Crusher', 'Firecracker', 'Guard Post'],
    keyTroops: ['Raged Barbarian', 'Sneaky Archer', 'Boxer Giant', 'Beta Minion', 'Bomber'],
    newBuildings: ['Guard Post', '2nd Firecracker', 'additional walls'],
    heroesAvailable: [],
    starLaboratory: true,
    description: 'the level where the Guard Post introduces defending troops and Beta Minions add air attack capabilities to your army',
    tier: 'beginner',
  },
  5: {
    name: 'Builder Hall 5',
    maxLevel: 5,
    keyDefenses: ['Cannon', 'Archer Tower', 'Double Cannon', 'Crusher', 'Firecracker', 'Guard Post', 'Multi Mortar'],
    keyTroops: ['Raged Barbarian', 'Sneaky Archer', 'Boxer Giant', 'Beta Minion', 'Bomber', 'Cannon Cart'],
    newBuildings: ['Multi Mortar', 'Battle Machine Altar', '2nd Double Cannon'],
    heroesAvailable: ['Battle Machine'],
    starLaboratory: true,
    description: 'a critical milestone that unlocks the Battle Machine hero with its Electric Hammer ability and the Multi Mortar for multi-directional splash damage',
    tier: 'intermediate',
  },
  6: {
    name: 'Builder Hall 6',
    maxLevel: 6,
    keyDefenses: ['Cannon', 'Archer Tower', 'Double Cannon', 'Crusher', 'Firecracker', 'Guard Post', 'Multi Mortar', 'Roaster'],
    keyTroops: ['Raged Barbarian', 'Sneaky Archer', 'Boxer Giant', 'Beta Minion', 'Bomber', 'Cannon Cart', 'Night Witch'],
    newBuildings: ['Roaster', '2nd Guard Post', 'additional traps'],
    heroesAvailable: ['Battle Machine'],
    starLaboratory: true,
    description: 'a strong defensive upgrade with the Roaster that shoots streams of fire at both ground and air units, and the Night Witch troop that summons Bats',
    tier: 'intermediate',
  },
  7: {
    name: 'Builder Hall 7',
    maxLevel: 7,
    keyDefenses: ['Cannon', 'Archer Tower', 'Double Cannon', 'Crusher', 'Firecracker', 'Guard Post', 'Multi Mortar', 'Roaster', 'Giant Cannon'],
    keyTroops: ['Raged Barbarian', 'Sneaky Archer', 'Boxer Giant', 'Beta Minion', 'Bomber', 'Cannon Cart', 'Night Witch', 'Drop Ship'],
    newBuildings: ['Giant Cannon', '2nd Crusher', 'additional Archer Tower'],
    heroesAvailable: ['Battle Machine'],
    starLaboratory: true,
    description: 'a powerful defensive level with the Giant Cannon that fires long-range explosive shells and a second Crusher, while Drop Ships provide tanking from the air',
    tier: 'intermediate',
  },
  8: {
    name: 'Builder Hall 8',
    maxLevel: 8,
    keyDefenses: ['Cannon', 'Archer Tower', 'Double Cannon', 'Crusher', 'Firecracker', 'Guard Post', 'Multi Mortar', 'Roaster', 'Giant Cannon', 'Mega Tesla'],
    keyTroops: ['Raged Barbarian', 'Sneaky Archer', 'Boxer Giant', 'Beta Minion', 'Bomber', 'Cannon Cart', 'Night Witch', 'Drop Ship', 'Super PEKKA', 'Hog Glider'],
    newBuildings: ['Mega Tesla', 'additional defenses and walls'],
    heroesAvailable: ['Battle Machine'],
    starLaboratory: true,
    description: 'a high-level Builder Base featuring the Mega Tesla that charges up to deal massive damage, the Super PEKKA with its explosive Overcharge ability on death, and the versatile Hog Glider',
    tier: 'advanced',
  },
  9: {
    name: 'Builder Hall 9',
    maxLevel: 9,
    keyDefenses: ['Cannon', 'Archer Tower', 'Double Cannon', 'Crusher', 'Firecracker', 'Guard Post', 'Multi Mortar', 'Roaster', 'Giant Cannon', 'Mega Tesla', 'Lava Launcher'],
    keyTroops: ['Raged Barbarian', 'Sneaky Archer', 'Boxer Giant', 'Beta Minion', 'Bomber', 'Cannon Cart', 'Night Witch', 'Drop Ship', 'Super PEKKA', 'Hog Glider', 'Electrofire Wizard'],
    newBuildings: ['O.T.T.O Hut', 'Lava Launcher', '2nd Mega Tesla'],
    heroesAvailable: ['Battle Machine'],
    ottoHut: true,
    starLaboratory: true,
    description: 'a game-changing level featuring the O.T.T.O Hut that unlocks a second builder for your Home Village, the Lava Launcher that shoots lava over walls, and the Electrofire Wizard with dual attack modes',
    tier: 'advanced',
  },
  10: {
    name: 'Builder Hall 10',
    maxLevel: 10,
    keyDefenses: ['Cannon', 'Archer Tower', 'Double Cannon', 'Crusher', 'Firecracker', 'Guard Post', 'Multi Mortar', 'Roaster', 'Giant Cannon', 'Mega Tesla', 'Lava Launcher', 'X-Bow'],
    keyTroops: ['Raged Barbarian', 'Sneaky Archer', 'Boxer Giant', 'Beta Minion', 'Bomber', 'Cannon Cart', 'Night Witch', 'Drop Ship', 'Super PEKKA', 'Hog Glider', 'Electrofire Wizard', 'Power PEKKA'],
    newBuildings: ['X-Bow', '2nd Lava Launcher', 'additional high-level defenses'],
    heroesAvailable: ['Battle Machine'],
    ottoHut: true,
    starLaboratory: true,
    description: 'the maximum Builder Hall level featuring the X-Bow for rapid-fire long-range defense, the Power PEKKA with its devastating charge attack, and maximum-level defenses across the board',
    tier: 'advanced',
  },
};

// -----------------------------------------------------------------------------
// EXPORTS (more will be added in subsequent days)
// -----------------------------------------------------------------------------
module.exports = {
  TOWN_HALL_DATA,
  BUILDER_HALL_DATA,
};
