// Centralized image management for Game365Hub
// All images are controlled from this single file
// To update an image, just change the URL here

export const images = {
  // Site branding (local — hardcoded)
  logo: "/logo.png",
  favicon: "/favicon.png",

  // Game hero images & logos
  games: {
    coc: {
      hero: "/images/games/clash-of-clans.jpg",
      logo: "https://i.pinimg.com/564x/98/92/8c/98928c82f78bdd50c5a28d8fa4633035.jpg",
      featured: "/images/games/coc-featured.jpg",
    },
    brawlStars: {
      hero: "/images/games/brawl-stars.webp",
      logo: "https://logodownload.org/wp-content/uploads/2021/11/brawl-stars-logo.png",
    },
    clashRoyale: {
      hero: "/images/games/clash-royale.jpg",
      logo: "https://static.wikia.nocookie.net/logopedia/images/4/47/ClashRoyaleNewAppIcon.png/revision/latest/scale-to-width-down/250?cb=20240425150654",
    },
    freeFire: {
      hero: "/images/games/free-fire.png",
      logo: "https://fontmeme.com/images/garena-free-fire-font.jpg",
    },
    pubg: {
      hero: "/images/games/pubg.jpg",
      logo: "https://play-lh.googleusercontent.com/_hITCaObfE2LSkWq9_ydYMmUXxVfexoRc5qA8GJy0GtSg_ee3ZKqwGPGa7KOjuG2j7E",
    },
  },

  // Town Hall images (from coc.guide — verified working PNGs)
  townHalls: {
    7: "https://coc.guide/static/imgs/other/town-hall-7.png",
    8: "https://coc.guide/static/imgs/other/town-hall-8.png",
    9: "https://coc.guide/static/imgs/other/town-hall-9.png",
    10: "https://coc.guide/static/imgs/other/town-hall-10.png",
    11: "https://coc.guide/static/imgs/other/town-hall-11.png",
    12: "https://coc.guide/static/imgs/other/town-hall-12.png",
    13: "https://coc.guide/static/imgs/other/town-hall-13.png",
    14: "https://coc.guide/static/imgs/other/town-hall-14.png",
    15: "https://coc.guide/static/imgs/other/town-hall-15.png",
    16: "https://coc.guide/static/imgs/other/town-hall-16.png",
    17: "https://coc.guide/static/imgs/other/town-hall-17.png",
    18: "https://cocbases.com/wp-content/themes/astra-child/images/th18.png",
  } as Record<number, string>,

  // Builder Hall images (from coc.guide — "town-hall2" = Builder Hall)
  builderHalls: {
    2: "https://coc.guide/static/imgs/other/town-hall2-2.png",
    3: "https://coc.guide/static/imgs/other/town-hall2-3.png",
    4: "https://coc.guide/static/imgs/other/town-hall2-4.png",
    5: "https://coc.guide/static/imgs/other/town-hall2-5.png",
    6: "https://coc.guide/static/imgs/other/town-hall2-6.png",
    7: "https://coc.guide/static/imgs/other/town-hall2-7.png",
    8: "https://coc.guide/static/imgs/other/town-hall2-8.png",
    9: "https://coc.guide/static/imgs/other/town-hall2-9.png",
    10: "https://coc.guide/static/imgs/other/town-hall2-10.png",
  } as Record<number, string>,

  // Blog article images (centralized)
  blog: {
    // Best Offline Games article
    "best-offline-games-featured": "https://i.ibb.co.com/r2f2VhsP/Chat-GPT-Image-Mar-8-2026-02-29-52-PM.png",
    "minecraft": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT62a53_ciTa35_N86nuk_edKJOV3rvLQAZUg&s",
    "stardew-valley": "https://www.stardewvalley.net/wp-content/uploads/2018/12/Multiplayer_Screenshot2-1.png",
    "monument-valley": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1927720/header.jpg",
    "altos-odyssey": "https://images.squarespace-cdn.com/content/v1/5f367f7c07f2f334e6c26710/1623418490408-XMVAWHV9LQ1Z9M3E0GQB/AO_TLC_KeyArt.png",
    "dead-cells": "https://dnm.nflximg.net/api/v6/2DuQlx0fM4wd1nzqm5BFBi6ILa8/AAAAQZLqxzozxryfwd7nm3K52azQFpjStyZPXx5Uu0zuHgJvvRO5EKriwAopNzSMej_6jxYVME95X4Sz0bmPRAusKRJCPjKEm_4RSh0Exo38fqr2En0KXJTZDnLrmjfLi5TOhCXgAQRbv2ka9l9AEQ.jpg?r=43e",
    "terraria": "https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/store/software/switch/70010000001702/dac3a26570b5ca1ddf703bf0add7cc7c527f71a2b56521baf69e20c7a573c610",
    "plague-inc": "https://assets.nintendo.com/image/upload/q_auto/f_auto/store/software/switch/70010000015517/d2f7dd044608a7a4f565eb2c9245b1c9fc66638c4c85739b12a63307130cfed2",
    "limbo": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/48000/header.jpg",
    "subway-surfers": "https://cdn.prod.website-files.com/65956e2711516206d2d1258f/68935ad12d5971baff22b805_Subway-surfers-characters-0-550x309.webp",
    "temple-run-2": "https://i.ytimg.com/vi/9aK2zoFBbKY/maxresdefault.jpg",
    "shadow-fight-3": "https://play-lh.googleusercontent.com/57JMKLkzF1sLNU0xqznbUry-xJq97X_KZefMbZwPEqFvd4g1y7Lm4L6tTv8esgak5A=w526-h296-rw",
    "asphalt-9": "https://prod-images.blacknut.net/61ea8d499233174193b8a5a2_hd.jpg",
    "crossy-road": "https://assets.nintendo.com/image/upload/q_auto/f_auto/store/software/switch/70010000072145/fa968b70b171de04b5ba564e1f67a231f58f190de856fb074db5aebf3720cc2f",
    "fruit-ninja": "https://cdn.prod.website-files.com/5fa23905123118739c5e21e2/66fb362949bd26dcef72f1d3_64dd8a5de4ae723b46abd674_FNCBG%20(1).jpg",
    "jetpack-joyride": "https://upload.wikimedia.org/wikipedia/en/9/90/Jetpack_Joyride_iOS.png",
    "cut-the-rope": "https://cdn.aptoide.com/imgs/2/8/e/28e5c069f1c3581f84e9bfac07205c61_fgraphic.png",
    "plants-vs-zombies": "https://play-lh.googleusercontent.com/ph545UB376SD-E8FJTBs0bldxYVFfKN3gri1tlbhFRWX-GkQFduARQcURxq8LSUvZCY=w526-h296-rw",
    "geometry-dash": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/322170/capsule_616x353.jpg?t=1703006148",
    "hill-climb-racing": "https://fingersoft.com/app/uploads/2022/04/2b-downloads-announcement-blog.jpg",
    "badland": "https://play-lh.googleusercontent.com/9ke0Ow8xU2B0fAiRhkV9rm4jsNw_eDoHhF4tFWK3-8AW3ew1J4BmkXOfiqw1aS7CiCI=w526-h296-rw",
    // Best Mobile Games 2026 article
    "best-mobile-games-featured": "https://cdn.mos.cms.futurecdn.net/6g3gfqcFEciKX6xqKw2tuC-1920-80.jpg",
    "genshin-impact": "https://media.wired.com/photos/5f74d2f4df8a35780989d792/3:2/w_2560%2Cc_limit/Genshin%2520Impact%2520_Keyart.png",
    "cod-mobile": "https://assets.gqindia.com/photos/5d933f025d883c0008e2df1b/master/pass/call%20of%20duty.jpg",
    "pubg-mobile": "https://www.gamespot.com/a/uploads/original/3/37852/3936747-pubgmobile2.jpg",
    "clash-of-clans": "https://gamesbeat.com/wp-content/uploads/2025/05/Clash-of-Clans-14.png",
    "brawl-stars": "https://games.lol/wp-content/uploads/2021/01/brawlers-gameplay.jpg",
    "clash-royale": "https://res.ldrescdn.com/faq/images/en/d8771531-d4be-4ac0-bbce-cef9ffc4a4d9.jpg?x-oss-process=image/format,webp/quality,Q_100/resize,w_800",
    "among-us": "https://sm.ign.com/ign_za/gallery/a/among-us-s/among-us-screenshots_f65x.jpg",
    "roblox": "https://images.rbxcdn.com/28ab48fcd5d5b19b03c126d2b6aef4b8.jpg",
    "honkai-star-rail": "https://kotaku.com/app/uploads/2024/09/c6832bd7fe5d9a0e05b3de4003253102.jpg",
    "diablo-immortal": "https://blz-contentstack-images.akamaized.net/v3/assets/blt77f4425de611b362/bltbc19204794f2a2fc/6865a67d6616e577f55942d6/di-open-graph_druid_enus.webp",
    "wild-rift": "https://play-lh.googleusercontent.com/2MVyQfLeEcKJE-ADgZJ4DvkfQcWoD52-DP9DYaGm0BhdyBztFITonnQyhpiRWzWvdBDD-NkkK2hYxxJI3GPuQFE=w648-h364-rw",
    "apex-legends-mobile": "https://images.axios.com/ewjSN60_iZk1LV0LCxPMvnVJ6tE=/0x0:2524x1420/1920x1080/2023/02/02/1675373320460.png",
    "pokemon-go": "https://lh3.googleusercontent.com/UFkIzWn5-MMK76LdARZPqR7-Uf0aNTLLdsCGN1sTHINe6QUWhuf4NDqRq4GKdVAdj57ILO_4gKqeQbaQmJ_gen3jbg0bYvjf3Ww",
    "candy-crush": "https://store-images.s-microsoft.com/image/apps.52397.13510798882606697.1816f804-e7fd-4295-9275-23dec3563baf.2ef7ec2d-2e37-489e-b6ac-b5f5e44d429c?q=90&w=480&h=270",
    // Best Horror Games 2026 article
    "horror-games-featured": "https://www.gamespot.com/a/uploads/scale_medium/1601/16018044/4645175-horror-games.jpg",
    "granny": "https://play-lh.googleusercontent.com/XPM8u_fQrERAQFNp1byQgCphu6_q_WSrJutTm2PF9iQBYbOhVu3ubliUxHaoZVdhyro=w526-h296-rw",
    "eyes-scary-thriller": "https://games.lol/wp-content/uploads/2020/11/eyes-scary-thriller-download-full-version.jpg",
    "dead-by-daylight": "https://static0.thegamerimages.com/wordpress/wp-content/uploads/2020/04/Dead-By-Daylight-Mobile-Killer.jpg?q=50&fit=crop&w=825&dpr=1.5",
    "identity-v": "https://cdn.topuplive.com/cdn-cgi/image/quality=low,format=webp/uploads/images/goods/20250430/1746015374_uALuySxQX8.jpg",
    "poppy-playtime": "https://upload.wikimedia.org/wikipedia/en/b/b6/Poppy_Playtime_cover.jpg",
    "fnaf": "https://brockpress.com/wp-content/uploads/2025/12/FNAF2-by-Andrea-a.png",
    "little-nightmares": "https://i.ytimg.com/vi/TIF8aCkblc4/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCEf7WIeCa1JVYkAEpR_GdRtR3AKg",
    "bendy-ink-machine": "https://i.ytimg.com/vi/howi4QrTC7g/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAmW9b5nUXgYUjuXrMkYxbwGjkXhQ",
    "into-the-dead-2": "https://i.ytimg.com/vi/s-5YPH56cQU/maxresdefault.jpg",
    "alien-isolation": "https://images.gog-statics.com/9f9372be93a325d16bff965889a3e136a6fd80ef1f4f62ca3468b733dcdf1e79.jpg",
    "amnesia": "https://static0.thegamerimages.com/wordpress/wp-content/uploads/2022/05/Amnesia-Rebirth-References-to-Older-Games-Split-Featured-The-Shadow-Tasi-and-the-Dark-Descent-Loading-Screen.jpg",
    "slendrina": "https://i.ytimg.com/vi/BqQikI9Uk9Y/maxresdefault.jpg",
    "the-room": "https://pbs.twimg.com/media/FKG0hXvXEAIehIs.jpg",
    "distraint": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/395170/capsule_616x353.jpg?t=1732098890",
    "oxenfree": "https://static1.gamespot.com/uploads/original/1547/15470456/2991426-sreens_cymk_tower.jpg",
    // Best Free Mobile Games 2026 article
    "free-games-featured": "https://i0.wp.com/mobilegamer.biz/wp-content/uploads/2026/01/top-downloads.png?fit=1024%2C461&ssl=1",
    "stumble-guys": "https://www.nintendo.com/eu/media/images/assets/nintendo_switch_games/stumbleguys/16x9_StumbleGuys.jpg",
    "archero": "https://www.androidauthority.com/wp-content/uploads/2020/02/Archero-cheats-and-hacks-guide.jpg",
    "soul-knight": "https://imag.malavida.com/mvimgbig/download-fs/soul-knight-21455-15.jpg",
    "pixel-dungeon": "https://play-lh.googleusercontent.com/I6Ccvac69MqPOubAY9ZcOJdN8Y0ZUm0Bfu81N33qOPBZw3hYXdwm_z8A_jvUPl5vEQ=w526-h296-rw",
    "sky-children-of-light": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2325290/a86fe4b80aec6e9e5414581d48e3679f270012aa/capsule_616x353.jpg?t=1772238230",
    "legends-of-runeterra": "https://www.macworld.com/wp-content/uploads/2023/01/lor-gameplay-100842589-orig.jpg?quality=50&strip=all",
    "brawlhalla": "https://i.ytimg.com/vi/WpPkmplf62A/maxresdefault.jpg",
    "pokemon-unite": "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_1.5/c_scale,w_500/store/software/switch/70010000043292/94e5214877b2f50ba6cb708be712fcf393f4fc7fb0aa1ee9d28a62c4f389237b",
    "standoff-2": "https://cdn-www.bluestacks.com/bs-images/585dc040905f07044546795f379e0ba3.jpeg",
    "mighty-doom": "https://play-lh.googleusercontent.com/Ec69ntaapB9b3QZ6SImdpFrQ5-2aaBHIJnYJaEmDTiO6VhjY8MssGRMAFPXTygwKqH9JZr-PQUqZ=w1296-h2160-rw",
    "grimvalor": "https://play-lh.googleusercontent.com/hxUvET73CF8SGYElCzmjsfhXBANlmsbRBq_30bkLyRL6sZOOIq3NRRIvBtYhWKx0Ow=w526-h296-rw",
    "slay-the-spire": "https://preview.redd.it/can-we-talk-about-the-insane-difficulty-of-slay-the-spire-2-v0-mshdm2gc01ng1.png?auto=webp&s=809738b58790d491e87a1cec417f56f9a4ae97d7",
    // Best Multiplayer Mobile Games 2026 article
    "multiplayer-games-featured": "https://approov.io/hubfs/blog_banners/Mobile_gaming.webp",
    "mario-kart-tour": "https://i.ytimg.com/vi/Bk7EhC-s5vI/maxresdefault.jpg",
    "minecraft-multiplayer": "https://www.gamesbap.com/wp-content/uploads/2022/02/Play-Multiplayer-on-Minecraft.jpg",
    "fortnite-mobile": "https://upload.wikimedia.org/wikipedia/en/2/28/Battling_in_fortnite.jpg",
    "rocket-league-sideswipe": "https://www.gamespot.com/a/uploads/original/1601/16018044/3913278-rls_keyart.jpg",
    "clash-mini": "https://supercell.com/images/06b75a838d18c59cd633824dff3bd82d/news_ingress_clashmini.jpg",
    "squad-busters": "https://www.gamereactor.eu/media/06/squadbusters_4290643b.jpg",
    "overwatch-2-mobile": "https://static0.thegamerimages.com/wordpress/wp-content/uploads/2024/10/overwatch-2-mobile.jpg?w=1600&h=900&fit=crop",
    "golf-clash": "https://cdn.aptoide.com/imgs/1/3/4/134a4be3796eead8df632f4b0cdec848_fgraphic.png",
    "words-with-friends": "https://www.androidauthority.com/wp-content/uploads/2017/11/Words-With-Friends-2.jpg",
    "8-ball-pool": "https://play-lh.googleusercontent.com/4nYOVq-PXWMTNRfKrk6p4m1MDt__rUjEKQqwMOo5wJ1ZgnPS--REiV3a2gCUjW0zu7TTwfbXUaiFlVU0yNLf=w648-h364-rw",
    "ludo-king": "https://i.ytimg.com/vi/A3fkqC3nZO8/maxresdefault.jpg",
    // Best Strategy Mobile Games 2026 article
    "strategy-games-featured": "https://i.ytimg.com/vi/0Ss8lfyUZg0/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBDWZTHjziXMrZTCqNtgXWPyrZCUA",
    "kingdom-rush": "https://digitalchumps.com/wp-content/uploads/2024/07/kingdom-rush-5-1.jpg?x82355",
    "bloons-td-6": "https://i.ytimg.com/vi/wp4T1wmsR40/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAACeaw1REpsLP_90YcJQSKQ_usMA",
    "rise-of-kingdoms": "https://cdn-www.bluestacks.com/bs-images/Rise-of-Kingdoms_Free-to-Play-Guide_EN_1.jpg",
    "civilization-vi": "https://d250f2ux8pmbq4.cloudfront.net/uploads/screenshot/image/1009/mobile_civVI-iphone-activeresearch.jpg",
    "xcom-2": "https://play-lh.googleusercontent.com/IOy0NvjLhDGpO5HggBYaVWjf07sYRTTeJ_pPnxVxKrHFZo5Xf8dqWGMLOP-EUAVC3JY=w526-h296-rw",
    "bad-north": "https://play-lh.googleusercontent.com/Z544wHp8XSjdpsjZarkYCfpNd9x6R7TACuD_6iKe3ppcsJEjvsooBJSVw7acdRROP6et=w526-h296-rw",
    "northgard": "https://play-lh.googleusercontent.com/h5JlFq4hJLglIldhQKBBNviiKJ9Gn15OlQB_cF6WQFz_igMEbtri6VP0plxBU-XdMQ=w526-h296-rw",
    "total-war-medieval-ii": "https://www.pockettactics.com/wp-content/sites/pockettactics/2022/04/total-war-medieval-2-mobile-review-1.jpg",
    "polytopia": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/874390/header.jpg?t=1772241079",
    "mindustry": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1127400/header.jpg",
    "iron-marines": "https://i.ytimg.com/vi/pWRdJUmkQ4c/maxresdefault.jpg",
    // Best Racing Mobile Games 2026 article
    "racing-games-featured": "https://static0.dualshockersimages.com/wordpress/wp-content/uploads/wm/2023/08/featured-image-for-best-mobile-racing-games-asphalt-9-mario-kart-tour-hell-rider-from-left-to-right.jpg?w=1600&h=1200&fit=crop",
    "real-racing-3": "https://media.contentapi.ea.com/content/dam/eacom/RR3/images/2020/09/r3-blog-notes-image.jpg.adapt.crop16x9.575p.jpg",
    "nfs-no-limits": "https://play-lh.googleusercontent.com/Y0oNvrknUwwCKcyYCeTCIItD1mq0M5ORGBl1hIblQVJ1Wqfeh16YqEuGCW6ohOCejg=w526-h296-rw",
    "csr-racing-2": "https://play-lh.googleusercontent.com/z0JEPR8JM1fSdFdFsuWwdg-361zGSD-zkrU_LSQp501T_VJyJ4CBX_S7eiRRT3cu8i8=w526-h296-rw",
    "rush-rally-3": "https://play-lh.googleusercontent.com/FSdW0ytXI185RowW9DqV6TXJGAKWTnCg8jZcKjdDEkVGexTLMBW2dYBIM6zr0zPYBkA-=w526-h296-rw",
    "grid-autosport": "https://play-lh.googleusercontent.com/HpAF2Oi9bMJdEBCcSp6vsy0e5eOeW0U1ne1U_sq1DYoC4KkcYJmcj2JyP38cljWwRQ=w526-h296-rw",
    "beach-buggy-racing-2": "https://i.ytimg.com/vi/at3RgV56FIo/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCZkbJ7I1SQUw1cV2GnT5g7Iuc_jg",
    "horizon-chase": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/389860/header.jpg",
    "carx-drift-racing-2": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1826420/15ebe5ced3771416673dd157695aaed349e61a92/capsule_616x353.jpg?t=1771422363",
    "f1-mobile-racing": "https://media.formula1.com/image/upload/c_lfill,w_3392/q_auto/v1740000000/content/dam/fom-website/manual/Misc/F1%20Game/MobileGame/Logo.webp",
    "road-rally": "https://static.wikia.nocookie.net/disney/images/2/21/3-5_RoadRally-1038x576.jpg/revision/latest?cb=20190801024715",
    "traffic-rider": "https://play-lh.googleusercontent.com/8UNnY1_KQIZIeKq5RQ9voPh3WKUrDxP7T93cojd1Q6K9QIs7H22CRzdJ7wBG_8-fnqQ=w526-h296-rw",
    "kart-rush": "https://play-lh.googleusercontent.com/DCPFtlm7j40TH8dTQVfDyRLtHA9OpthYq84yTKeD0sjezi6fWbxVggT2H5-9lIbR52Y=w526-h296-rw",
    // Best Puzzle Mobile Games 2026 article
    "puzzle-games-featured": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2023/01/untitled-design-11.jpg",
    "monument-valley-3": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3132930/header.jpg",
    "baba-is-you": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/736260/header.jpg",
    "the-room-old-sins": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1361320/header.jpg",
    "superliminal": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1049410/header.jpg",
    "unpacking": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1135690/header.jpg",
    "there-is-no-game": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1240210/header.jpg",
    "a-little-to-the-left": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1629520/header.jpg",
    "lara-croft-go": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/540840/header.jpg",
    "hitman-go": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/427820/header.jpg",
    "mekorama": "https://www.mekorama.com/press/mekorama-icon-512x512.png",
    "wordle": "https://nytimeswordle.net/wp-content/uploads/2023/01/wordle-game-2-1024x580.jpg",
    "2048": "https://imgs.crazygames.com/games/2048/cover_1x1-1707828857318.png?format=auto&quality=100&metadata=none&width=1200",
    "threes": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1818570/header.jpg",
    "brain-out": "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/46/49/10/46491036-3dbe-eb97-3ef3-d05ceb9673be/AppIcon-1x_U007emarketing-0-8-0-85-220-0.png/1200x630wa.png",
    "chants-of-sennaar": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1931770/header.jpg",
    // Best RPG Mobile Games 2026 article
    "rpg-games-featured": "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800",
    "final-fantasy-vii": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2484110/header.jpg",
    "octopath-traveler": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/921570/header.jpg",
    "raid-shadow-legends": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2333480/header.jpg",
    "summoners-war": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2426960/header.jpg",
    "afk-arena": "https://afkarena.lilith.com/images/slogimg2_bg_pc.jpg",
    "monster-hunter-stories": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1543030/header.jpg",
    "another-eden": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1252600/header.jpg",
    "guardian-tales": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2200670/header.jpg",
    "star-wars-kotor": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/32370/header.jpg",
    "chrono-trigger": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/613830/header.jpg",
    "albion-online": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/761890/header.jpg",
    // Best Simulation Mobile Games 2026 article
    "simulation-games-featured": "https://images.unsplash.com/photo-1631983856389-88c4010e41c0?w=1200&q=80",
    "the-sims-mobile": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1222670/header.jpg",
    "pocket-city-2": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3566200/3111dc4e45f3e4a25c616f26272e6990f153c1ff/header.jpg?t=1743343915",
    "my-time-at-portia": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/666140/header.jpg",
    "cities-skylines": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/255710/header.jpg",
    "good-pizza-great-pizza": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1448400/header.jpg",
    "game-dev-tycoon": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/239820/header.jpg",
    "fallout-shelter": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/588430/header.jpg",
    "roller-coaster-tycoon-3": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1368820/header.jpg",
    "worldbox": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1206560/header.jpg",
    "mini-motorways": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1127500/header.jpg",
    "game-dev-story": "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1539870/header.jpg",
    "township": "https://upload.wikimedia.org/wikipedia/en/f/f7/Township_App_Icon.jpg",
    "bitlife": "https://static.wikia.nocookie.net/bitlife-life-simulator/images/2/29/6A7344E7-2EE7-41A4-B147-CA5E9BB4C514.png/revision/latest?cb=20200119203111",
    // Clash of Clans Beginners Guide 2026 article
    "coc-beginners-featured": "https://supercell.com/images/ae58a39e76410b4ae9c2bea65d4a584d/hero_bg_clashofclans_.fae7c799.jpg",
    "coc-town-hall": "https://coc.guide/static/imgs/other/town-hall-12.png",
    "coc-builders": "https://supercell.com/images/ee75acf3c95a2dff060cfcb9fdd5b8d8/games_clashofclans_video_comeback_builder_thumbnail.6ed75f3e.webp",
    "coc-troops": "https://coc.guide/static/imgs/troop/barbarian.png",
    "coc-clan-castle": "https://supercell.com/images/857356cdd36607911a5c7c4a9dfaeaf2/games_clashofclans_video_eightclansenter_thumbnail.9917c72f.webp",
    "coc-heroes": "https://coc.guide/static/imgs/hero/barbarian-king.png",
    "coc-resources": "https://supercell.com/images/67ef84ede1652fff54ae1972147eae78/games_clashofclans_video_goblinwizard_thumbnail.5d105814.webp",
    "coc-base-layout": "https://supercell.com/images/e6f04ebde8a85ae7d5f9a0a851e664fa/bg_intro_clashofclans.134fece1.webp",
    // TH18 Attack Strategies Guide
    "th18-attack-featured": "https://cocbases.com/wp-content/themes/astra-child/images/th18.png",
    "th18-town-hall": "https://cocbases.com/wp-content/themes/astra-child/images/th18.png",
    "th18-root-rider": "https://coc.guide/static/imgs/troop/root-rider.png",
    "th18-electro-titan": "https://coc.guide/static/imgs/troop/electro-titan.png",
    "th18-yeti": "https://coc.guide/static/imgs/troop/yeti.png",
    "th18-golem": "https://coc.guide/static/imgs/troop/golem.png",
    "th18-lava-hound": "https://coc.guide/static/imgs/troop/ice-hound.png",
    "th18-dragon": "https://coc.guide/static/imgs/troop/dragon.png",
    "th18-barbarian-king": "https://coc.guide/static/imgs/hero/barbarian-king.png",
    "th18-archer-queen": "https://coc.guide/static/imgs/hero/archer-queen.png",
    // TH17 Attack Strategies Guide
    "th17-attack-featured": "https://coc.guide/static/imgs/other/town-hall-17.png",
    "th17-town-hall": "https://coc.guide/static/imgs/other/town-hall-17.png",
    "th17-apprentice-warden": "https://coc.guide/static/imgs/troop/apprentice-warden.png",
    "th17-witch": "https://coc.guide/static/imgs/troop/ice-golem.png",
    "th17-bowler": "https://coc.guide/static/imgs/troop/bowler.png",
    "th17-balloon": "https://coc.guide/static/imgs/troop/balloon.png",
    "th17-electro-dragon": "https://coc.guide/static/imgs/troop/electro-dragon.png",
    "th17-hog-rider": "https://coc.guide/static/imgs/troop/super-hog-rider.png",
    // TH16 Attack Strategies Guide
    "th16-attack-featured": "https://coc.guide/static/imgs/other/town-hall-16.png",
    "th16-town-hall": "https://coc.guide/static/imgs/other/town-hall-16.png",
    "th16-root-rider": "https://coc.guide/static/imgs/troop/root-rider.png",
    "th16-pekka": "https://coc.guide/static/imgs/troop/pekka.png",
    "th16-bowler": "https://coc.guide/static/imgs/troop/bowler.png",
    "th16-electro-dragon": "https://coc.guide/static/imgs/troop/electro-dragon.png",
    "th16-miner": "https://coc.guide/static/imgs/troop/miner.png",
    "th16-golem": "https://coc.guide/static/imgs/troop/golem.png",
    // Army Compositions Guide
    "army-comp-featured": "https://supercell.com/images/ae58a39e76410b4ae9c2bea65d4a584d/hero_bg_clashofclans_.fae7c799.jpg",
    "army-barbarian": "https://coc.guide/static/imgs/troop/barbarian.png",
    "army-dragon": "https://coc.guide/static/imgs/troop/dragon.png",
    "army-pekka": "https://coc.guide/static/imgs/troop/pekka.png",
    "army-golem": "https://coc.guide/static/imgs/troop/golem.png",
    "army-bowler": "https://coc.guide/static/imgs/troop/bowler.png",
    "army-electro-dragon": "https://coc.guide/static/imgs/troop/electro-dragon.png",
    "army-root-rider": "https://coc.guide/static/imgs/troop/root-rider.png",
    "army-miner": "https://coc.guide/static/imgs/troop/miner.png",
    // F2P Maxing Guide
    "f2p-guide-featured": "https://supercell.com/images/67ef84ede1652fff54ae1972147eae78/games_clashofclans_video_goblinwizard_thumbnail.5d105814.webp",
    "f2p-builder": "https://coc.guide/static/imgs/troop/wall-breaker.png",
    "f2p-lab": "https://coc.guide/static/imgs/troop/goblin.png",
    "f2p-clan-games": "https://supercell.com/images/857356cdd36607911a5c7c4a9dfaeaf2/games_clashofclans_video_eightclansenter_thumbnail.9917c72f.webp",
    "f2p-sneaky-goblin": "https://coc.guide/static/imgs/troop/goblin.png",
    "f2p-wall": "https://coc.guide/static/imgs/troop/golem.png",
    // CWL Strategy Guide
    "cwl-guide-featured": "https://supercell.com/images/e6f04ebde8a85ae7d5f9a0a851e664fa/bg_intro_clashofclans.134fece1.webp",
    "cwl-war-base": "https://coc.guide/static/imgs/troop/wizard.png",
    "cwl-lineup": "https://coc.guide/static/imgs/hero/archer-queen.png",
    "cwl-attack": "https://coc.guide/static/imgs/troop/root-rider.png",
    "cwl-medals": "https://coc.guide/static/imgs/hero/barbarian-king.png",
    "cwl-strategy": "https://coc.guide/static/imgs/troop/healer.png",
    // Hero Equipment Rankings Guide
    "hero-equip-featured": "https://supercell.com/images/ee75acf3c95a2dff060cfcb9fdd5b8d8/games_clashofclans_video_comeback_builder_thumbnail.6ed75f3e.webp",
    "hero-equip-king": "https://coc.guide/static/imgs/hero/barbarian-king.png",
    "hero-equip-queen": "https://coc.guide/static/imgs/hero/archer-queen.png",
    "hero-equip-warden": "https://coc.guide/static/imgs/troop/healer.png",
    "hero-equip-champion": "https://coc.guide/static/imgs/troop/dragon.png",
    "hero-equip-minion": "https://coc.guide/static/imgs/troop/wizard.png",
    // Legend League Push Guide
    "legend-featured": "https://supercell.com/images/ae58a39e76410b4ae9c2bea65d4a584d/hero_bg_clashofclans_.fae7c799.jpg",
    "legend-trophy": "https://coc.guide/static/imgs/hero/barbarian-king.png",
    "legend-base": "https://coc.guide/static/imgs/troop/electro-dragon.png",
    "legend-attack": "https://coc.guide/static/imgs/troop/root-rider.png",
    "legend-defense": "https://coc.guide/static/imgs/troop/pekka.png",
    // Defensive CC Troops Guide
    "def-cc-featured": "https://supercell.com/images/857356cdd36607911a5c7c4a9dfaeaf2/games_clashofclans_video_eightclansenter_thumbnail.9917c72f.webp",
    "def-cc-dragon": "https://coc.guide/static/imgs/troop/dragon.png",
    "def-cc-edrag": "https://coc.guide/static/imgs/troop/electro-dragon.png",
    "def-cc-golem": "https://coc.guide/static/imgs/troop/golem.png",
    "def-cc-bowler": "https://coc.guide/static/imgs/troop/bowler.png",
  } as Record<string, string>,

  // Base layout images — real screenshots from CoC base sites
  bases: {
    // TH18 (25 bases)
    "th18-war-1": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_181.jpg",
    "th18-war-2": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_180.jpg",
    "th18-war-3": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_179.jpg",
    "th18-war-4": "https://clashofclans-layouts.com/pics/th18_plans/war/preview/th18_war_10.jpg",
    "th18-war-5": "https://clashofclans-layouts.com/pics/th18_plans/war/preview/th18_war_9.jpg",
    "th18-war-6": "https://clashofclans-layouts.com/pics/th18_plans/war/preview/th18_war_8.jpg",
    "th18-war-7": "https://clashofclans-layouts.com/pics/th18_plans/war/preview/th18_war_7.jpg",
    "th18-war-8": "https://clashofclans-layouts.com/pics/th18_plans/war/preview/th18_war_6.jpg",
    "th18-war-9": "https://clashofclans-layouts.com/pics/th18_plans/war/preview/th18_war_5.jpg",
    "th18-trophy-1": "https://clashofclans-layouts.com/pics/th17_plans/defence/preview/th17_defence_70.jpg",
    "th18-trophy-2": "https://clashofclans-layouts.com/pics/th18_plans/defence/preview/th18_defence_10.jpg",
    "th18-trophy-3": "https://clashofclans-layouts.com/pics/th18_plans/defence/preview/th18_defence_9.jpg",
    "th18-trophy-4": "https://clashofclans-layouts.com/pics/th18_plans/defence/preview/th18_defence_8.jpg",
    "th18-trophy-5": "https://clashofclans-layouts.com/pics/th18_plans/defence/preview/th18_defence_7.jpg",
    "th18-farming-1": "https://clashofclans-layouts.com/pics/th17_plans/farm/preview/th17_farm_40.jpg",
    "th18-farming-2": "https://clashofclans-layouts.com/pics/th18_plans/farm/preview/th18_farm_10.jpg",
    "th18-farming-3": "https://clashofclans-layouts.com/pics/th18_plans/farm/preview/th18_farm_9.jpg",
    "th18-farming-4": "https://clashofclans-layouts.com/pics/th18_plans/farm/preview/th18_farm_8.jpg",
    "th18-farming-5": "https://clashofclans-layouts.com/pics/th18_plans/farm/preview/th18_farm_7.jpg",
    "th18-cwl-1": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_178.jpg",
    "th18-cwl-2": "https://clashofclans-layouts.com/pics/th18_plans/war/preview/th18_war_4.jpg",
    "th18-cwl-3": "https://clashofclans-layouts.com/pics/th18_plans/war/preview/th18_war_3.jpg",
    "th18-cwl-4": "https://clashofclans-layouts.com/pics/th18_plans/war/preview/th18_war_2.jpg",
    "th18-hybrid-2": "https://clashofclans-layouts.com/pics/th18_plans/defence/preview/th18_defence_6.jpg",
    "th18-hybrid-3": "https://clashofclans-layouts.com/pics/th18_plans/defence/preview/th18_defence_5.jpg",
    "th18-anti3-2": "https://clashofclans-layouts.com/pics/th18_plans/war/preview/th18_war_1.jpg",
    "th18-anti3-3": "https://clashofclans-layouts.com/pics/th18_plans/defence/preview/th18_defence_4.jpg",
    "th18-anti3-4": "https://clashofclans-layouts.com/pics/th18_plans/defence/preview/th18_defence_3.jpg",
    // TH17
    "th17-war-1": "https://media.oneclash.com/layout/thumbniled-1772650264421.jpg",
    "th17-war-2": "https://media.oneclash.com/layout/thumbniled-1771643915560.jpg",
    "th17-war-3": "https://media.oneclash.com/layout/thumbniled-1771059913779.jpg",
    "th17-war-4": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_177.jpg",
    "th17-war-5": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_176.jpg",
    "th17-war-6": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_175.jpg",
    "th17-war-7": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_174.jpg",
    "th17-war-8": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_173.jpg",
    "th17-trophy-1": "https://clashofclans-layouts.com/pics/th17_plans/defence/preview/th17_defence_61.jpg",
    "th17-trophy-2": "https://media.oneclash.com/layout/thumbniled-A5086975-1AFF-4069-8CAD-70697FA70D73.jpg",
    "th17-farming-1": "https://clashofclans-layouts.com/pics/th17_plans/farm/preview/th17_farm_40.jpg",
    "th17-farming-2": "https://media.oneclash.com/layout/thumbniled-1767625154139.jpg",
    "th17-cwl-1": "https://media.oneclash.com/layout/thumbniled-1766846034742.jpg",
    "th17-cwl-2": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_172.jpg",
    "th17-hybrid-1": "https://media.oneclash.com/layout/thumbniled-9E9B24AF-7A30-4221-B6E4-199009ED059C.jpg",
    "th17-anti3-1": "https://media.oneclash.com/layout/thumbniled-1763650954023.jpg",
    // TH17 extra (war 9-20, trophy 3-6, farming 3-6, cwl 3-6, hybrid 2-4, anti3 2-4)
    "th17-war-9": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_171.jpg",
    "th17-war-10": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_170.jpg",
    "th17-war-11": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_169.jpg",
    "th17-war-12": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_168.jpg",
    "th17-war-13": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_167.jpg",
    "th17-war-14": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_166.jpg",
    "th17-war-15": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_165.jpg",
    "th17-war-16": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_164.jpg",
    "th17-war-17": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_163.jpg",
    "th17-war-18": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_162.jpg",
    "th17-war-19": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_161.jpg",
    "th17-war-20": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_160.jpg",
    "th17-trophy-3": "https://clashofclans-layouts.com/pics/th17_plans/defence/preview/th17_defence_60.jpg",
    "th17-trophy-4": "https://clashofclans-layouts.com/pics/th17_plans/defence/preview/th17_defence_59.jpg",
    "th17-trophy-5": "https://clashofclans-layouts.com/pics/th17_plans/defence/preview/th17_defence_58.jpg",
    "th17-trophy-6": "https://clashofclans-layouts.com/pics/th17_plans/defence/preview/th17_defence_57.jpg",
    "th17-farming-3": "https://clashofclans-layouts.com/pics/th17_plans/farm/preview/th17_farm_39.jpg",
    "th17-farming-4": "https://clashofclans-layouts.com/pics/th17_plans/farm/preview/th17_farm_38.jpg",
    "th17-farming-5": "https://clashofclans-layouts.com/pics/th17_plans/farm/preview/th17_farm_37.jpg",
    "th17-farming-6": "https://clashofclans-layouts.com/pics/th17_plans/farm/preview/th17_farm_36.jpg",
    "th17-cwl-3": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_159.jpg",
    "th17-cwl-4": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_158.jpg",
    "th17-cwl-5": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_157.jpg",
    "th17-cwl-6": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_156.jpg",
    "th17-hybrid-2": "https://clashofclans-layouts.com/pics/th17_plans/defence/preview/th17_defence_56.jpg",
    "th17-hybrid-3": "https://clashofclans-layouts.com/pics/th17_plans/defence/preview/th17_defence_55.jpg",
    "th17-hybrid-4": "https://clashofclans-layouts.com/pics/th17_plans/defence/preview/th17_defence_54.jpg",
    "th17-anti3-2": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_155.jpg",
    "th17-anti3-3": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_154.jpg",
    "th17-anti3-4": "https://clashofclans-layouts.com/pics/th17_plans/war/preview/th17_war_153.jpg",
    // TH16 (25 bases)
    "th16-war-1": "https://clashofclans-layouts.com/pics/th16_plans/war/preview/th16_war_124.jpg",
    "th16-war-2": "https://clashofclans-layouts.com/pics/th16_plans/war/preview/th16_war_123.jpg",
    "th16-war-3": "https://clashofclans-layouts.com/pics/th16_plans/war/preview/th16_war_122.jpg",
    "th16-war-4": "https://clashofclans-layouts.com/pics/th16_plans/war/preview/th16_war_121.jpg",
    "th16-war-5": "https://clashofclans-layouts.com/pics/th16_plans/war/preview/th16_war_120.jpg",
    "th16-war-6": "https://clashofclans-layouts.com/pics/th16_plans/war/preview/th16_war_119.jpg",
    "th16-war-7": "https://clashofclans-layouts.com/pics/th16_plans/war/preview/th16_war_118.jpg",
    "th16-war-8": "https://clashofclans-layouts.com/pics/th16_plans/war/preview/th16_war_117.jpg",
    "th16-trophy-1": "https://clashofclans-layouts.com/pics/th16_plans/defence/preview/th16_defence_70.jpg",
    "th16-trophy-2": "https://clashofclans-layouts.com/pics/th16_plans/defence/preview/th16_defence_69.jpg",
    "th16-trophy-3": "https://clashofclans-layouts.com/pics/th16_plans/defence/preview/th16_defence_55.jpg",
    "th16-trophy-4": "https://clashofclans-layouts.com/pics/th16_plans/defence/preview/th16_defence_54.jpg",
    "th16-farming-1": "https://clashofclans-layouts.com/pics/th16_plans/farm/preview/th16_farm_31.jpg",
    "th16-farming-2": "https://media.oneclash.com/layout/thumbniled-9030.jpg",
    "th16-farming-3": "https://clashofclans-layouts.com/pics/th16_plans/farm/preview/th16_farm_30.jpg",
    "th16-farming-4": "https://clashofclans-layouts.com/pics/th16_plans/farm/preview/th16_farm_29.jpg",
    "th16-farming-5": "https://clashofclans-layouts.com/pics/th16_plans/farm/preview/th16_farm_28.jpg",
    "th16-hybrid-1": "https://media.oneclash.com/layout/thumbniled-9029.jpg",
    "th16-hybrid-2": "https://clashofclans-layouts.com/pics/th16_plans/defence/preview/th16_defence_53.jpg",
    "th16-hybrid-3": "https://clashofclans-layouts.com/pics/th16_plans/defence/preview/th16_defence_52.jpg",
    "th16-hybrid-4": "https://clashofclans-layouts.com/pics/th16_plans/defence/preview/th16_defence_51.jpg",
    "th16-cwl-1": "https://media.oneclash.com/layout/thumbniled-9028.jpg",
    "th16-cwl-2": "https://clashofclans-layouts.com/pics/th16_plans/war/preview/th16_war_116.jpg",
    "th16-cwl-3": "https://clashofclans-layouts.com/pics/th16_plans/war/preview/th16_war_115.jpg",
    "th16-anti3-1": "https://clashofclans-layouts.com/pics/th16_plans/defence/preview/th16_defence_68.jpg",
    "th16-anti3-2": "https://clashofclans-layouts.com/pics/th16_plans/defence/preview/th16_defence_67.jpg",
    "th16-anti3-3": "https://clashofclans-layouts.com/pics/th16_plans/war/preview/th16_war_114.jpg",
    // TH15 (25 bases)
    "th15-war-1": "https://clashofclans-layouts.com/pics/th15_plans/war/preview/th15_war_131.jpg",
    "th15-war-2": "https://clashofclans-layouts.com/pics/th15_plans/war/preview/th15_war_130.jpg",
    "th15-war-3": "https://clashofclans-layouts.com/pics/th15_plans/war/preview/th15_war_129.jpg",
    "th15-war-4": "https://clashofclans-layouts.com/pics/th15_plans/war/preview/th15_war_128.jpg",
    "th15-war-5": "https://clashofclans-layouts.com/pics/th15_plans/war/preview/th15_war_127.jpg",
    "th15-war-6": "https://clashofclans-layouts.com/pics/th15_plans/war/preview/th15_war_126.jpg",
    "th15-war-7": "https://clashofclans-layouts.com/pics/th15_plans/war/preview/th15_war_125.jpg",
    "th15-war-8": "https://clashofclans-layouts.com/pics/th15_plans/war/preview/th15_war_124.jpg",
    "th15-trophy-1": "https://clashofclans-layouts.com/pics/th15_plans/defence/preview/th15_defence_84.jpg",
    "th15-trophy-2": "https://clashofclans-layouts.com/pics/th15_plans/defence/preview/th15_defence_83.jpg",
    "th15-trophy-3": "https://clashofclans-layouts.com/pics/th15_plans/defence/preview/th15_defence_81.jpg",
    "th15-trophy-4": "https://clashofclans-layouts.com/pics/th15_plans/defence/preview/th15_defence_80.jpg",
    "th15-farming-1": "https://media.oneclash.com/layout/thumbniled-1772262554975.jpg",
    "th15-farming-2": "https://media.oneclash.com/layout/thumbniled-1771685060994.jpg",
    "th15-farming-3": "https://clashofclans-layouts.com/pics/th15_plans/farm/preview/th15_farm_35.jpg",
    "th15-farming-4": "https://clashofclans-layouts.com/pics/th15_plans/farm/preview/th15_farm_34.jpg",
    "th15-farming-5": "https://clashofclans-layouts.com/pics/th15_plans/farm/preview/th15_farm_33.jpg",
    "th15-cwl-1": "https://clashofclans-layouts.com/pics/th15_plans/defence/preview/th15_defence_82.jpg",
    "th15-cwl-2": "https://clashofclans-layouts.com/pics/th15_plans/war/preview/th15_war_123.jpg",
    "th15-cwl-3": "https://clashofclans-layouts.com/pics/th15_plans/war/preview/th15_war_122.jpg",
    "th15-hybrid-1": "https://media.oneclash.com/layout/thumbniled-1771591652866.jpg",
    "th15-hybrid-2": "https://clashofclans-layouts.com/pics/th15_plans/defence/preview/th15_defence_79.jpg",
    "th15-hybrid-3": "https://clashofclans-layouts.com/pics/th15_plans/defence/preview/th15_defence_78.jpg",
    "th15-anti3-1": "https://media.oneclash.com/layout/thumbniled-1771513204686.jpg",
    "th15-anti3-2": "https://clashofclans-layouts.com/pics/th15_plans/defence/preview/th15_defence_77.jpg",
    "th15-anti3-3": "https://clashofclans-layouts.com/pics/th15_plans/defence/preview/th15_defence_76.jpg",
    // TH14 (25 bases)
    "th14-war-1": "https://clashofclans-layouts.com/pics/th14_plans/war/preview/th14_war_229.jpg",
    "th14-war-2": "https://clashofclans-layouts.com/pics/th14_plans/war/preview/th14_war_228.jpg",
    "th14-war-3": "https://clashofclans-layouts.com/pics/th14_plans/war/preview/th14_war_227.jpg",
    "th14-war-4": "https://clashofclans-layouts.com/pics/th14_plans/war/preview/th14_war_226.jpg",
    "th14-war-5": "https://clashofclans-layouts.com/pics/th14_plans/war/preview/th14_war_225.jpg",
    "th14-war-6": "https://clashofclans-layouts.com/pics/th14_plans/war/preview/th14_war_224.jpg",
    "th14-war-7": "https://clashofclans-layouts.com/pics/th14_plans/war/preview/th14_war_223.jpg",
    "th14-trophy-1": "https://clashofclans-layouts.com/pics/th14_plans/defence/preview/th14_defence_86.jpg",
    "th14-trophy-2": "https://clashofclans-layouts.com/pics/th14_plans/defence/preview/th14_defence_85.jpg",
    "th14-trophy-3": "https://clashofclans-layouts.com/pics/th14_plans/defence/preview/th14_defence_84.jpg",
    "th14-trophy-4": "https://clashofclans-layouts.com/pics/th14_plans/defence/preview/th14_defence_83.jpg",
    "th14-farming-1": "https://clashofclans-layouts.com/pics/th14_plans/farm/preview/th14_farm_53.jpg",
    "th14-farming-2": "https://media.oneclash.com/layout/thumbniled-1769770890575.jpg",
    "th14-farming-3": "https://clashofclans-layouts.com/pics/th14_plans/farm/preview/th14_farm_52.jpg",
    "th14-farming-4": "https://clashofclans-layouts.com/pics/th14_plans/farm/preview/th14_farm_51.jpg",
    "th14-farming-5": "https://clashofclans-layouts.com/pics/th14_plans/farm/preview/th14_farm_50.jpg",
    "th14-cwl-1": "https://media.oneclash.com/layout/thumbniled-1769593593649.jpg",
    "th14-cwl-2": "https://clashofclans-layouts.com/pics/th14_plans/war/preview/th14_war_222.jpg",
    "th14-cwl-3": "https://clashofclans-layouts.com/pics/th14_plans/war/preview/th14_war_221.jpg",
    "th14-hybrid-1": "https://media.oneclash.com/layout/thumbniled-1769369230050.jpg",
    "th14-hybrid-2": "https://clashofclans-layouts.com/pics/th14_plans/defence/preview/th14_defence_82.jpg",
    "th14-hybrid-3": "https://clashofclans-layouts.com/pics/th14_plans/defence/preview/th14_defence_81.jpg",
    "th14-hybrid-4": "https://clashofclans-layouts.com/pics/th14_plans/defence/preview/th14_defence_80.jpg",
    "th14-anti3-1": "https://clashofclans-layouts.com/pics/th14_plans/war/preview/th14_war_220.jpg",
    "th14-anti3-2": "https://clashofclans-layouts.com/pics/th14_plans/defence/preview/th14_defence_79.jpg",
    // TH13 (25 bases)
    "th13-war-1": "https://clashofclans-layouts.com/pics/th13_plans/war/preview/th13_war_298.jpg",
    "th13-war-2": "https://clashofclans-layouts.com/pics/th13_plans/war/preview/th13_war_297.jpg",
    "th13-war-3": "https://clashofclans-layouts.com/pics/th13_plans/war/preview/th13_war_296.jpg",
    "th13-war-4": "https://clashofclans-layouts.com/pics/th13_plans/war/preview/th13_war_295.jpg",
    "th13-war-5": "https://clashofclans-layouts.com/pics/th13_plans/war/preview/th13_war_294.jpg",
    "th13-war-6": "https://clashofclans-layouts.com/pics/th13_plans/war/preview/th13_war_293.jpg",
    "th13-war-7": "https://clashofclans-layouts.com/pics/th13_plans/war/preview/th13_war_292.jpg",
    "th13-trophy-1": "https://clashofclans-layouts.com/pics/th13_plans/defence/preview/th13_defence_138.jpg",
    "th13-trophy-2": "https://clashofclans-layouts.com/pics/th13_plans/defence/preview/th13_defence_135.jpg",
    "th13-trophy-3": "https://clashofclans-layouts.com/pics/th13_plans/defence/preview/th13_defence_134.jpg",
    "th13-trophy-4": "https://clashofclans-layouts.com/pics/th13_plans/defence/preview/th13_defence_133.jpg",
    "th13-farming-1": "https://clashofclans-layouts.com/pics/th13_plans/farm/preview/th13_farm_79.jpg",
    "th13-farming-2": "https://clashofclans-layouts.com/pics/th13_plans/farm/preview/th13_farm_78.jpg",
    "th13-farming-3": "https://clashofclans-layouts.com/pics/th13_plans/farm/preview/th13_farm_77.jpg",
    "th13-farming-4": "https://clashofclans-layouts.com/pics/th13_plans/farm/preview/th13_farm_76.jpg",
    "th13-farming-5": "https://clashofclans-layouts.com/pics/th13_plans/farm/preview/th13_farm_75.jpg",
    "th13-hybrid-1": "https://media.oneclash.com/layout/thumbniled-3D95377D-0D2C-4285-A5F3-FA5591936F55.jpg",
    "th13-hybrid-2": "https://clashofclans-layouts.com/pics/th13_plans/defence/preview/th13_defence_132.jpg",
    "th13-hybrid-3": "https://clashofclans-layouts.com/pics/th13_plans/defence/preview/th13_defence_131.jpg",
    "th13-cwl-1": "https://media.oneclash.com/layout/thumbniled-1FF72A70-2055-4D62-A9F7-14F5CCE2785F.jpg",
    "th13-cwl-2": "https://clashofclans-layouts.com/pics/th13_plans/war/preview/th13_war_291.jpg",
    "th13-cwl-3": "https://clashofclans-layouts.com/pics/th13_plans/war/preview/th13_war_290.jpg",
    "th13-anti3-1": "https://clashofclans-layouts.com/pics/th13_plans/defence/preview/th13_defence_136.jpg",
    "th13-anti3-2": "https://clashofclans-layouts.com/pics/th13_plans/defence/preview/th13_defence_130.jpg",
    "th13-anti3-3": "https://clashofclans-layouts.com/pics/th13_plans/defence/preview/th13_defence_129.jpg",
    // TH12 (25 bases)
    "th12-war-1": "https://clashofclans-layouts.com/pics/th12_plans/war/preview/th12_war_196.jpg",
    "th12-war-2": "https://clashofclans-layouts.com/pics/th12_plans/war/preview/th12_war_195.jpg",
    "th12-war-3": "https://clashofclans-layouts.com/pics/th12_plans/war/preview/th12_war_193.jpg",
    "th12-war-4": "https://clashofclans-layouts.com/pics/th12_plans/war/preview/th12_war_192.jpg",
    "th12-war-5": "https://clashofclans-layouts.com/pics/th12_plans/war/preview/th12_war_191.jpg",
    "th12-war-6": "https://clashofclans-layouts.com/pics/th12_plans/war/preview/th12_war_190.jpg",
    "th12-war-7": "https://clashofclans-layouts.com/pics/th12_plans/war/preview/th12_war_189.jpg",
    "th12-trophy-1": "https://clashofclans-layouts.com/pics/th12_plans/defence/preview/th12_defence_82.jpg",
    "th12-trophy-2": "https://clashofclans-layouts.com/pics/th12_plans/defence/preview/th12_defence_80.jpg",
    "th12-trophy-3": "https://clashofclans-layouts.com/pics/th12_plans/defence/preview/th12_defence_79.jpg",
    "th12-trophy-4": "https://clashofclans-layouts.com/pics/th12_plans/defence/preview/th12_defence_78.jpg",
    "th12-farming-1": "https://clashofclans-layouts.com/pics/th12_plans/farm/preview/th12_farm_47.jpg",
    "th12-farming-2": "https://clashofclans-layouts.com/pics/th12_plans/farm/preview/th12_farm_46.jpg",
    "th12-farming-3": "https://clashofclans-layouts.com/pics/th12_plans/farm/preview/th12_farm_45.jpg",
    "th12-farming-4": "https://clashofclans-layouts.com/pics/th12_plans/farm/preview/th12_farm_44.jpg",
    "th12-farming-5": "https://clashofclans-layouts.com/pics/th12_plans/farm/preview/th12_farm_43.jpg",
    "th12-cwl-1": "https://clashofclans-layouts.com/pics/th12_plans/war/preview/th12_war_194.jpg",
    "th12-cwl-2": "https://clashofclans-layouts.com/pics/th12_plans/war/preview/th12_war_188.jpg",
    "th12-cwl-3": "https://clashofclans-layouts.com/pics/th12_plans/war/preview/th12_war_187.jpg",
    "th12-hybrid-1": "https://clashofclans-layouts.com/pics/th12_plans/defence/preview/th12_defence_81.jpg",
    "th12-hybrid-2": "https://clashofclans-layouts.com/pics/th12_plans/defence/preview/th12_defence_77.jpg",
    "th12-hybrid-3": "https://clashofclans-layouts.com/pics/th12_plans/defence/preview/th12_defence_76.jpg",
    "th12-anti3-1": "https://clashofclans-layouts.com/pics/th12_plans/war/preview/th12_war_186.jpg",
    "th12-anti3-2": "https://clashofclans-layouts.com/pics/th12_plans/defence/preview/th12_defence_75.jpg",
    // TH11 (25 bases)
    "th11-war-1": "https://clashofclans-layouts.com/pics/th11_plans/war/preview/th11_war_198.jpg",
    "th11-war-2": "https://clashofclans-layouts.com/pics/th11_plans/war/preview/th11_war_197.jpg",
    "th11-war-3": "https://clashofclans-layouts.com/pics/th11_plans/war/preview/th11_war_196.jpg",
    "th11-war-4": "https://clashofclans-layouts.com/pics/th11_plans/war/preview/th11_war_195.jpg",
    "th11-war-5": "https://clashofclans-layouts.com/pics/th11_plans/war/preview/th11_war_194.jpg",
    "th11-war-6": "https://clashofclans-layouts.com/pics/th11_plans/war/preview/th11_war_193.jpg",
    "th11-war-7": "https://clashofclans-layouts.com/pics/th11_plans/war/preview/th11_war_192.jpg",
    "th11-trophy-1": "https://clashofclans-layouts.com/pics/th11_plans/defence/preview/th11_defence_84.jpg",
    "th11-trophy-2": "https://clashofclans-layouts.com/pics/th11_plans/defence/preview/th11_defence_82.jpg",
    "th11-trophy-3": "https://clashofclans-layouts.com/pics/th11_plans/defence/preview/th11_defence_81.jpg",
    "th11-trophy-4": "https://clashofclans-layouts.com/pics/th11_plans/defence/preview/th11_defence_80.jpg",
    "th11-farming-1": "https://clashofclans-layouts.com/pics/th11_plans/farm/preview/th11_farm_38.jpg",
    "th11-farming-2": "https://clashofclans-layouts.com/pics/th11_plans/farm/preview/th11_farm_37.jpg",
    "th11-farming-3": "https://clashofclans-layouts.com/pics/th11_plans/farm/preview/th11_farm_36.jpg",
    "th11-farming-4": "https://clashofclans-layouts.com/pics/th11_plans/farm/preview/th11_farm_35.jpg",
    "th11-farming-5": "https://clashofclans-layouts.com/pics/th11_plans/farm/preview/th11_farm_34.jpg",
    "th11-hybrid-1": "https://clashofclans-layouts.com/pics/th11_plans/defence/preview/th11_defence_83.jpg",
    "th11-hybrid-2": "https://clashofclans-layouts.com/pics/th11_plans/defence/preview/th11_defence_79.jpg",
    "th11-hybrid-3": "https://clashofclans-layouts.com/pics/th11_plans/defence/preview/th11_defence_78.jpg",
    "th11-cwl-1": "https://clashofclans-layouts.com/pics/th11_plans/war/preview/th11_war_191.jpg",
    "th11-cwl-2": "https://clashofclans-layouts.com/pics/th11_plans/war/preview/th11_war_190.jpg",
    "th11-cwl-3": "https://clashofclans-layouts.com/pics/th11_plans/war/preview/th11_war_189.jpg",
    "th11-anti3-1": "https://clashofclans-layouts.com/pics/th11_plans/defence/preview/th11_defence_77.jpg",
    "th11-anti3-2": "https://clashofclans-layouts.com/pics/th11_plans/war/preview/th11_war_188.jpg",
    // TH10 (25 bases)
    "th10-war-1": "https://clashofclans-layouts.com/pics/th10_plans/war/preview/th10_war_186.jpg",
    "th10-war-2": "https://clashofclans-layouts.com/pics/th10_plans/war/preview/th10_war_185.jpg",
    "th10-war-3": "https://clashofclans-layouts.com/pics/th10_plans/war/preview/th10_war_184.jpg",
    "th10-war-4": "https://clashofclans-layouts.com/pics/th10_plans/war/preview/th10_war_183.jpg",
    "th10-war-5": "https://clashofclans-layouts.com/pics/th10_plans/war/preview/th10_war_182.jpg",
    "th10-war-6": "https://clashofclans-layouts.com/pics/th10_plans/war/preview/th10_war_181.jpg",
    "th10-war-7": "https://clashofclans-layouts.com/pics/th10_plans/war/preview/th10_war_180.jpg",
    "th10-trophy-1": "https://clashofclans-layouts.com/pics/th10_plans/defence/preview/th10_defence_78.jpg",
    "th10-trophy-2": "https://clashofclans-layouts.com/pics/th10_plans/defence/preview/th10_defence_76.jpg",
    "th10-trophy-3": "https://clashofclans-layouts.com/pics/th10_plans/defence/preview/th10_defence_75.jpg",
    "th10-trophy-4": "https://clashofclans-layouts.com/pics/th10_plans/defence/preview/th10_defence_74.jpg",
    "th10-farming-1": "https://clashofclans-layouts.com/pics/th10_plans/farm/preview/th10_farm_42.jpg",
    "th10-farming-2": "https://clashofclans-layouts.com/pics/th10_plans/farm/preview/th10_farm_41.jpg",
    "th10-farming-3": "https://clashofclans-layouts.com/pics/th10_plans/farm/preview/th10_farm_40.jpg",
    "th10-farming-4": "https://clashofclans-layouts.com/pics/th10_plans/farm/preview/th10_farm_39.jpg",
    "th10-farming-5": "https://clashofclans-layouts.com/pics/th10_plans/farm/preview/th10_farm_38.jpg",
    "th10-hybrid-1": "https://clashofclans-layouts.com/pics/th10_plans/defence/preview/th10_defence_77.jpg",
    "th10-hybrid-2": "https://clashofclans-layouts.com/pics/th10_plans/defence/preview/th10_defence_73.jpg",
    "th10-hybrid-3": "https://clashofclans-layouts.com/pics/th10_plans/defence/preview/th10_defence_72.jpg",
    "th10-cwl-1": "https://clashofclans-layouts.com/pics/th10_plans/war/preview/th10_war_179.jpg",
    "th10-cwl-2": "https://clashofclans-layouts.com/pics/th10_plans/war/preview/th10_war_178.jpg",
    "th10-anti3-1": "https://clashofclans-layouts.com/pics/th10_plans/war/preview/th10_war_177.jpg",
    "th10-anti3-2": "https://clashofclans-layouts.com/pics/th10_plans/defence/preview/th10_defence_71.jpg",
    // TH9 (25 bases)
    "th9-war-1": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_168.jpg",
    "th9-war-2": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_167.jpg",
    "th9-war-3": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_125.jpg",
    "th9-war-4": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_124.jpg",
    "th9-war-5": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_123.jpg",
    "th9-war-6": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_122.jpg",
    "th9-war-7": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_121.jpg",
    "th9-farming-1": "https://clashofclans-layouts.com/pics/th9_plans/farm/preview/th9_farm_36.jpg",
    "th9-farming-2": "https://clashofclans-layouts.com/pics/th9_plans/farm/preview/th9_farm_35.jpg",
    "th9-farming-3": "https://clashofclans-layouts.com/pics/th9_plans/farm/preview/th9_farm_34.jpg",
    "th9-farming-4": "https://clashofclans-layouts.com/pics/th9_plans/farm/preview/th9_farm_33.jpg",
    "th9-farming-5": "https://clashofclans-layouts.com/pics/th9_plans/farm/preview/th9_farm_32.jpg",
    "th9-trophy-1": "https://clashofclans-layouts.com/pics/th9_plans/defence/preview/th9_defence_72.jpg",
    "th9-trophy-2": "https://clashofclans-layouts.com/pics/th9_plans/defence/preview/th9_defence_71.jpg",
    "th9-trophy-3": "https://clashofclans-layouts.com/pics/th9_plans/defence/preview/th9_defence_69.jpg",
    "th9-trophy-4": "https://clashofclans-layouts.com/pics/th9_plans/defence/preview/th9_defence_68.jpg",
    "th9-hybrid-1": "https://clashofclans-layouts.com/pics/th9_plans/defence/preview/th9_defence_67.jpg",
    "th9-hybrid-2": "https://clashofclans-layouts.com/pics/th9_plans/defence/preview/th9_defence_66.jpg",
    "th9-hybrid-3": "https://clashofclans-layouts.com/pics/th9_plans/defence/preview/th9_defence_65.jpg",
    "th9-hybrid-4": "https://clashofclans-layouts.com/pics/th9_plans/defence/preview/th9_defence_64.jpg",
    "th9-anti3-1": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_120.jpg",
    "th9-anti3-2": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_119.jpg",
    "th9-anti3-3": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_118.jpg",
    "th9-cwl-1": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_117.jpg",
    "th9-cwl-2": "https://clashofclans-layouts.com/pics/th9_plans/war/preview/th9_war_116.jpg",
    // TH8 (25 bases)
    "th8-war-1": "https://clashofclans-layouts.com/pics/th8_plans/war/preview/th8_war_124.jpg",
    "th8-war-2": "https://clashofclans-layouts.com/pics/th8_plans/war/preview/th8_war_123.jpg",
    "th8-war-3": "https://clashofclans-layouts.com/pics/th8_plans/war/preview/th8_war_122.jpg",
    "th8-war-4": "https://clashofclans-layouts.com/pics/th8_plans/war/preview/th8_war_121.jpg",
    "th8-war-5": "https://clashofclans-layouts.com/pics/th8_plans/war/preview/th8_war_120.jpg",
    "th8-war-6": "https://clashofclans-layouts.com/pics/th8_plans/war/preview/th8_war_119.jpg",
    "th8-war-7": "https://clashofclans-layouts.com/pics/th8_plans/war/preview/th8_war_118.jpg",
    "th8-war-8": "https://clashofclans-layouts.com/pics/th8_plans/war/preview/th8_war_117.jpg",
    "th8-farming-1": "https://clashofclans-layouts.com/pics/th8_plans/farm/preview/th8_farm_28.jpg",
    "th8-farming-2": "https://clashofclans-layouts.com/pics/th8_plans/farm/preview/th8_farm_27.jpg",
    "th8-farming-3": "https://clashofclans-layouts.com/pics/th8_plans/farm/preview/th8_farm_26.jpg",
    "th8-farming-4": "https://clashofclans-layouts.com/pics/th8_plans/farm/preview/th8_farm_25.jpg",
    "th8-farming-5": "https://clashofclans-layouts.com/pics/th8_plans/farm/preview/th8_farm_24.jpg",
    "th8-farming-6": "https://clashofclans-layouts.com/pics/th8_plans/farm/preview/th8_farm_23.jpg",
    "th8-trophy-1": "https://clashofclans-layouts.com/pics/th8_plans/defence/preview/th8_defence_50.jpg",
    "th8-trophy-2": "https://clashofclans-layouts.com/pics/th8_plans/defence/preview/th8_defence_49.jpg",
    "th8-trophy-3": "https://clashofclans-layouts.com/pics/th8_plans/defence/preview/th8_defence_48.jpg",
    "th8-trophy-4": "https://clashofclans-layouts.com/pics/th8_plans/defence/preview/th8_defence_47.jpg",
    "th8-trophy-5": "https://clashofclans-layouts.com/pics/th8_plans/defence/preview/th8_defence_46.jpg",
    "th8-hybrid-1": "https://clashofclans-layouts.com/pics/th8_plans/defence/preview/th8_defence_45.jpg",
    "th8-hybrid-2": "https://clashofclans-layouts.com/pics/th8_plans/defence/preview/th8_defence_44.jpg",
    "th8-hybrid-3": "https://clashofclans-layouts.com/pics/th8_plans/defence/preview/th8_defence_43.jpg",
    "th8-anti3-1": "https://clashofclans-layouts.com/pics/th8_plans/war/preview/th8_war_116.jpg",
    "th8-anti3-2": "https://clashofclans-layouts.com/pics/th8_plans/war/preview/th8_war_115.jpg",
    "th8-anti3-3": "https://clashofclans-layouts.com/pics/th8_plans/war/preview/th8_war_114.jpg",
    // TH7 (25 bases)
    "th7-war-1": "https://clashofclans-layouts.com/pics/th7_plans/war/preview/th7_war_86.jpg",
    "th7-war-2": "https://clashofclans-layouts.com/pics/th7_plans/war/preview/th7_war_85.jpg",
    "th7-war-3": "https://clashofclans-layouts.com/pics/th7_plans/war/preview/th7_war_84.jpg",
    "th7-war-4": "https://clashofclans-layouts.com/pics/th7_plans/war/preview/th7_war_83.jpg",
    "th7-war-5": "https://clashofclans-layouts.com/pics/th7_plans/war/preview/th7_war_82.jpg",
    "th7-war-6": "https://clashofclans-layouts.com/pics/th7_plans/war/preview/th7_war_81.jpg",
    "th7-war-7": "https://clashofclans-layouts.com/pics/th7_plans/war/preview/th7_war_80.jpg",
    "th7-war-8": "https://clashofclans-layouts.com/pics/th7_plans/war/preview/th7_war_79.jpg",
    "th7-farming-1": "https://clashofclans-layouts.com/pics/th7_plans/farm/preview/th7_farm_22.jpg",
    "th7-farming-2": "https://clashofclans-layouts.com/pics/th7_plans/farm/preview/th7_farm_21.jpg",
    "th7-farming-3": "https://clashofclans-layouts.com/pics/th7_plans/farm/preview/th7_farm_20.jpg",
    "th7-farming-4": "https://clashofclans-layouts.com/pics/th7_plans/farm/preview/th7_farm_19.jpg",
    "th7-farming-5": "https://clashofclans-layouts.com/pics/th7_plans/farm/preview/th7_farm_18.jpg",
    "th7-farming-6": "https://clashofclans-layouts.com/pics/th7_plans/farm/preview/th7_farm_17.jpg",
    "th7-farming-7": "https://clashofclans-layouts.com/pics/th7_plans/farm/preview/th7_farm_16.jpg",
    "th7-trophy-1": "https://clashofclans-layouts.com/pics/th7_plans/defence/preview/th7_defence_25.jpg",
    "th7-trophy-2": "https://clashofclans-layouts.com/pics/th7_plans/defence/preview/th7_defence_24.jpg",
    "th7-trophy-3": "https://clashofclans-layouts.com/pics/th7_plans/defence/preview/th7_defence_23.jpg",
    "th7-trophy-4": "https://clashofclans-layouts.com/pics/th7_plans/defence/preview/th7_defence_22.jpg",
    "th7-trophy-5": "https://clashofclans-layouts.com/pics/th7_plans/defence/preview/th7_defence_21.jpg",
    "th7-hybrid-1": "https://clashofclans-layouts.com/pics/th7_plans/defence/preview/th7_defence_20.jpg",
    "th7-hybrid-2": "https://clashofclans-layouts.com/pics/th7_plans/defence/preview/th7_defence_19.jpg",
    "th7-hybrid-3": "https://clashofclans-layouts.com/pics/th7_plans/defence/preview/th7_defence_18.jpg",
    "th7-hybrid-4": "https://clashofclans-layouts.com/pics/th7_plans/defence/preview/th7_defence_17.jpg",
    "th7-hybrid-5": "https://clashofclans-layouts.com/pics/th7_plans/defence/preview/th7_defence_16.jpg",
  } as Record<string, string>,

  // Builder Base layout images — from clashofclans-layouts.com (defence type only)
  builderBases: {
    // BH3 (10 bases)
    "bh3-1": "https://clashofclans-layouts.com/pics/bh3_plans/defence/preview/bh3_defence_1.jpg",
    "bh3-2": "https://clashofclans-layouts.com/pics/bh3_plans/defence/preview/bh3_defence_2.jpg",
    "bh3-3": "https://clashofclans-layouts.com/pics/bh3_plans/defence/preview/bh3_defence_3.jpg",
    "bh3-4": "https://clashofclans-layouts.com/pics/bh3_plans/defence/preview/bh3_defence_4.jpg",
    "bh3-5": "https://clashofclans-layouts.com/pics/bh3_plans/defence/preview/bh3_defence_5.jpg",
    "bh3-6": "https://clashofclans-layouts.com/pics/bh3_plans/defence/preview/bh3_defence_6.jpg",
    "bh3-7": "https://clashofclans-layouts.com/pics/bh3_plans/defence/preview/bh3_defence_7.jpg",
    "bh3-8": "https://clashofclans-layouts.com/pics/bh3_plans/defence/preview/bh3_defence_8.jpg",
    "bh3-9": "https://clashofclans-layouts.com/pics/bh3_plans/defence/preview/bh3_defence_9.jpg",
    "bh3-10": "https://clashofclans-layouts.com/pics/bh3_plans/defence/preview/bh3_defence_10.jpg",
    // BH4 (10 bases)
    "bh4-1": "https://clashofclans-layouts.com/pics/bh4_plans/defence/preview/bh4_defence_1.jpg",
    "bh4-2": "https://clashofclans-layouts.com/pics/bh4_plans/defence/preview/bh4_defence_2.jpg",
    "bh4-3": "https://clashofclans-layouts.com/pics/bh4_plans/defence/preview/bh4_defence_3.jpg",
    "bh4-4": "https://clashofclans-layouts.com/pics/bh4_plans/defence/preview/bh4_defence_4.jpg",
    "bh4-5": "https://clashofclans-layouts.com/pics/bh4_plans/defence/preview/bh4_defence_5.jpg",
    "bh4-6": "https://clashofclans-layouts.com/pics/bh4_plans/defence/preview/bh4_defence_6.jpg",
    "bh4-7": "https://clashofclans-layouts.com/pics/bh4_plans/defence/preview/bh4_defence_7.jpg",
    "bh4-8": "https://clashofclans-layouts.com/pics/bh4_plans/defence/preview/bh4_defence_8.jpg",
    "bh4-9": "https://clashofclans-layouts.com/pics/bh4_plans/defence/preview/bh4_defence_9.jpg",
    "bh4-10": "https://clashofclans-layouts.com/pics/bh4_plans/defence/preview/bh4_defence_10.jpg",
    // BH5 (10 bases)
    "bh5-1": "https://clashofclans-layouts.com/pics/bh5_plans/defence/preview/bh5_defence_1.jpg",
    "bh5-2": "https://clashofclans-layouts.com/pics/bh5_plans/defence/preview/bh5_defence_2.jpg",
    "bh5-3": "https://clashofclans-layouts.com/pics/bh5_plans/defence/preview/bh5_defence_3.jpg",
    "bh5-4": "https://clashofclans-layouts.com/pics/bh5_plans/defence/preview/bh5_defence_4.jpg",
    "bh5-5": "https://clashofclans-layouts.com/pics/bh5_plans/defence/preview/bh5_defence_5.jpg",
    "bh5-6": "https://clashofclans-layouts.com/pics/bh5_plans/defence/preview/bh5_defence_6.jpg",
    "bh5-7": "https://clashofclans-layouts.com/pics/bh5_plans/defence/preview/bh5_defence_7.jpg",
    "bh5-8": "https://clashofclans-layouts.com/pics/bh5_plans/defence/preview/bh5_defence_8.jpg",
    "bh5-9": "https://clashofclans-layouts.com/pics/bh5_plans/defence/preview/bh5_defence_9.jpg",
    "bh5-10": "https://clashofclans-layouts.com/pics/bh5_plans/defence/preview/bh5_defence_10.jpg",
    // BH6 (10 bases)
    "bh6-1": "https://clashofclans-layouts.com/pics/bh6_plans/defence/preview/bh6_defence_1.jpg",
    "bh6-2": "https://clashofclans-layouts.com/pics/bh6_plans/defence/preview/bh6_defence_2.jpg",
    "bh6-3": "https://clashofclans-layouts.com/pics/bh6_plans/defence/preview/bh6_defence_3.jpg",
    "bh6-4": "https://clashofclans-layouts.com/pics/bh6_plans/defence/preview/bh6_defence_4.jpg",
    "bh6-5": "https://clashofclans-layouts.com/pics/bh6_plans/defence/preview/bh6_defence_5.jpg",
    "bh6-6": "https://clashofclans-layouts.com/pics/bh6_plans/defence/preview/bh6_defence_6.jpg",
    "bh6-7": "https://clashofclans-layouts.com/pics/bh6_plans/defence/preview/bh6_defence_7.jpg",
    "bh6-8": "https://clashofclans-layouts.com/pics/bh6_plans/defence/preview/bh6_defence_8.jpg",
    "bh6-9": "https://clashofclans-layouts.com/pics/bh6_plans/defence/preview/bh6_defence_9.jpg",
    "bh6-10": "https://clashofclans-layouts.com/pics/bh6_plans/defence/preview/bh6_defence_10.jpg",
    // BH7 (10 bases)
    "bh7-1": "https://clashofclans-layouts.com/pics/bh7_plans/defence/preview/bh7_defence_1.jpg",
    "bh7-2": "https://clashofclans-layouts.com/pics/bh7_plans/defence/preview/bh7_defence_2.jpg",
    "bh7-3": "https://clashofclans-layouts.com/pics/bh7_plans/defence/preview/bh7_defence_3.jpg",
    "bh7-4": "https://clashofclans-layouts.com/pics/bh7_plans/defence/preview/bh7_defence_4.jpg",
    "bh7-5": "https://clashofclans-layouts.com/pics/bh7_plans/defence/preview/bh7_defence_5.jpg",
    "bh7-6": "https://clashofclans-layouts.com/pics/bh7_plans/defence/preview/bh7_defence_6.jpg",
    "bh7-7": "https://clashofclans-layouts.com/pics/bh7_plans/defence/preview/bh7_defence_7.jpg",
    "bh7-8": "https://clashofclans-layouts.com/pics/bh7_plans/defence/preview/bh7_defence_8.jpg",
    "bh7-9": "https://clashofclans-layouts.com/pics/bh7_plans/defence/preview/bh7_defence_9.jpg",
    "bh7-10": "https://clashofclans-layouts.com/pics/bh7_plans/defence/preview/bh7_defence_10.jpg",
    // BH8 (12 bases)
    "bh8-1": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_1.jpg",
    "bh8-2": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_2.jpg",
    "bh8-3": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_3.jpg",
    "bh8-4": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_4.jpg",
    "bh8-5": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_5.jpg",
    "bh8-6": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_6.jpg",
    "bh8-7": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_7.jpg",
    "bh8-8": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_8.jpg",
    "bh8-9": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_9.jpg",
    "bh8-10": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_10.jpg",
    "bh8-11": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_11.jpg",
    "bh8-12": "https://clashofclans-layouts.com/pics/bh8_plans/defence/preview/bh8_defence_12.jpg",
    // BH9 (12 bases)
    "bh9-1": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_1.jpg",
    "bh9-2": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_2.jpg",
    "bh9-3": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_3.jpg",
    "bh9-4": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_4.jpg",
    "bh9-5": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_5.jpg",
    "bh9-6": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_6.jpg",
    "bh9-7": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_7.jpg",
    "bh9-8": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_8.jpg",
    "bh9-9": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_9.jpg",
    "bh9-10": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_10.jpg",
    "bh9-11": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_11.jpg",
    "bh9-12": "https://clashofclans-layouts.com/pics/bh9_plans/defence/preview/bh9_defence_12.jpg",
    // BH10 (12 bases)
    "bh10-1": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_1.jpg",
    "bh10-2": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_2.jpg",
    "bh10-3": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_3.jpg",
    "bh10-4": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_4.jpg",
    "bh10-5": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_5.jpg",
    "bh10-6": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_6.jpg",
    "bh10-7": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_7.jpg",
    "bh10-8": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_8.jpg",
    "bh10-9": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_9.jpg",
    "bh10-10": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_10.jpg",
    "bh10-11": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_11.jpg",
    "bh10-12": "https://clashofclans-layouts.com/pics/bh10_plans/defence/preview/bh10_defence_12.jpg",
  } as Record<string, string>,

  // Guide images (add as: "game/slug": "image-url")
  guides: {} as Record<string, string>,
};

// Helper to get image with fallback
export function getImage(path: string, fallback: string = "/images/games/clash-of-clans.jpg"): string {
  return path || fallback;
}
