// Clash Royale Cards Data Library

// Card Rarities
export const RARITIES = {
  common: { name: 'Common', color: '#B0B0B0', maxLevel: 14 },
  rare: { name: 'Rare', color: '#FF8C00', maxLevel: 14 },
  epic: { name: 'Epic', color: '#C800FF', maxLevel: 14 },
  legendary: { name: 'Legendary', color: '#FFD700', maxLevel: 14 },
  champion: { name: 'Champion', color: '#00BFFF', maxLevel: 14 },
};

// Card Types
export const CARD_TYPES = {
  troop: { name: 'Troop', icon: '⚔️', color: '#E74C3C' },
  spell: { name: 'Spell', icon: '✨', color: '#9B59B6' },
  building: { name: 'Building', icon: '🏰', color: '#3498DB' },
};

// Tier Rankings
export const TIERS = {
  S: { name: 'S Tier', description: 'Overpowered - Must use', color: '#FF4444' },
  A: { name: 'A Tier', description: 'Very strong meta picks', color: '#FF8C00' },
  B: { name: 'B Tier', description: 'Solid and reliable choices', color: '#FFD700' },
  C: { name: 'C Tier', description: 'Situational but viable', color: '#4CAF50' },
  D: { name: 'D Tier', description: 'Needs a buff', color: '#9E9E9E' },
};

// Arenas
export const ARENAS = [
  { id: 1, name: 'Goblin Stadium', trophies: 0 },
  { id: 2, name: 'Bone Pit', trophies: 300 },
  { id: 3, name: 'Barbarian Bowl', trophies: 600 },
  { id: 4, name: 'Spell Valley', trophies: 1000 },
  { id: 5, name: "Builder's Workshop", trophies: 1300 },
  { id: 6, name: "P.E.K.K.A's Playhouse", trophies: 1600 },
  { id: 7, name: 'Royal Arena', trophies: 2000 },
  { id: 8, name: 'Frozen Peak', trophies: 2300 },
  { id: 9, name: 'Jungle Arena', trophies: 2600 },
  { id: 10, name: 'Hog Mountain', trophies: 3000 },
  { id: 11, name: 'Electro Valley', trophies: 3400 },
  { id: 12, name: 'Spooky Town', trophies: 3800 },
  { id: 13, name: 'Rascals Hideout', trophies: 4200 },
  { id: 14, name: 'Serenity Peak', trophies: 4600 },
  { id: 15, name: 'Legendary Arena', trophies: 5000 },
];

// All Cards Data
export const CARDS = [
  // S Tier Cards
  {
    id: 'hog-rider',
    name: 'Hog Rider',
    type: 'troop',
    rarity: 'rare',
    elixir: 4,
    tier: 'S',
    useRate: 24.5,
    winRate: 54.2,
    description: 'Fast building-targeting troop. One of the most versatile win conditions in the game.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/hog-rider.png',
  },
  {
    id: 'fireball',
    name: 'Fireball',
    type: 'spell',
    rarity: 'rare',
    elixir: 4,
    tier: 'S',
    useRate: 28.3,
    winRate: 52.8,
    description: 'Versatile medium damage spell. Great for chip damage and clearing support troops.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/fireball.png',
  },
  {
    id: 'log',
    name: 'The Log',
    type: 'spell',
    rarity: 'legendary',
    elixir: 2,
    tier: 'S',
    useRate: 32.1,
    winRate: 53.5,
    description: 'Rolling log that pushes back and damages ground troops. Excellent value.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/the-log.png',
  },
  {
    id: 'archer-queen',
    name: 'Archer Queen',
    type: 'troop',
    rarity: 'champion',
    elixir: 5,
    tier: 'S',
    useRate: 18.7,
    winRate: 56.1,
    description: 'Champion that can turn invisible. Deadly when ability is activated.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/archer-queen.png',
  },
  {
    id: 'little-prince',
    name: 'Little Prince',
    type: 'troop',
    rarity: 'champion',
    elixir: 3,
    tier: 'S',
    useRate: 21.4,
    winRate: 55.8,
    description: 'Low cost champion with guardian ability. Excellent cycle card.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/little-prince.png',
  },
  {
    id: 'goblin-barrel',
    name: 'Goblin Barrel',
    type: 'spell',
    rarity: 'epic',
    elixir: 3,
    tier: 'S',
    useRate: 15.2,
    winRate: 54.7,
    description: 'Throws goblins anywhere on the map. Core of log bait decks.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/goblin-barrel.png',
  },

  // A Tier Cards
  {
    id: 'musketeer',
    name: 'Musketeer',
    type: 'troop',
    rarity: 'rare',
    elixir: 4,
    tier: 'A',
    useRate: 14.8,
    winRate: 52.1,
    description: 'Long range single target DPS. Staple in Hog and X-Bow decks.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/musketeer.png',
  },
  {
    id: 'knight',
    name: 'Knight',
    type: 'troop',
    rarity: 'common',
    elixir: 3,
    tier: 'A',
    useRate: 16.5,
    winRate: 51.8,
    description: 'Tanky mini-tank with great stats for cost. Reliable defensive option.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/knight.png',
  },
  {
    id: 'skeletons',
    name: 'Skeletons',
    type: 'troop',
    rarity: 'common',
    elixir: 1,
    tier: 'A',
    useRate: 19.2,
    winRate: 52.4,
    description: '1 elixir cycle card. Amazing value for distraction and DPS.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/skeletons.png',
  },
  {
    id: 'cannon',
    name: 'Cannon',
    type: 'building',
    rarity: 'common',
    elixir: 3,
    tier: 'A',
    useRate: 12.3,
    winRate: 51.5,
    description: 'Cheap defensive building. Pulls Hog Riders and Giants effectively.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/cannon.png',
  },
  {
    id: 'mini-pekka',
    name: 'Mini P.E.K.K.A',
    type: 'troop',
    rarity: 'rare',
    elixir: 4,
    tier: 'A',
    useRate: 11.7,
    winRate: 51.2,
    description: 'High single target DPS. Destroys tanks quickly.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/mini-pekka.png',
  },
  {
    id: 'golem',
    name: 'Golem',
    type: 'troop',
    rarity: 'epic',
    elixir: 8,
    tier: 'A',
    useRate: 8.5,
    winRate: 53.2,
    description: 'Massive tank that splits into Golemites. Devastating beatdown win condition.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/golem.png',
  },
  {
    id: 'baby-dragon',
    name: 'Baby Dragon',
    type: 'troop',
    rarity: 'epic',
    elixir: 4,
    tier: 'A',
    useRate: 13.4,
    winRate: 51.9,
    description: 'Flying splash damage troop. Great support card for beatdown.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/baby-dragon.png',
  },
  {
    id: 'electro-wizard',
    name: 'Electro Wizard',
    type: 'troop',
    rarity: 'legendary',
    elixir: 4,
    tier: 'A',
    useRate: 10.8,
    winRate: 52.6,
    description: 'Stuns enemies with each attack. Great vs Inferno and Sparky.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/electro-wizard.png',
  },
  {
    id: 'poison',
    name: 'Poison',
    type: 'spell',
    rarity: 'epic',
    elixir: 4,
    tier: 'A',
    useRate: 9.4,
    winRate: 52.3,
    description: 'Area denial spell. Slows and damages over time.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/poison.png',
  },
  {
    id: 'zap',
    name: 'Zap',
    type: 'spell',
    rarity: 'common',
    elixir: 2,
    tier: 'A',
    useRate: 22.1,
    winRate: 50.8,
    description: 'Instant stun spell. Resets Inferno and Sparky charges.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/zap.png',
  },

  // B Tier Cards
  {
    id: 'giant',
    name: 'Giant',
    type: 'troop',
    rarity: 'rare',
    elixir: 5,
    tier: 'B',
    useRate: 7.2,
    winRate: 50.5,
    description: 'Building-targeting tank. Classic F2P friendly win condition.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/giant.png',
  },
  {
    id: 'wizard',
    name: 'Wizard',
    type: 'troop',
    rarity: 'rare',
    elixir: 5,
    tier: 'B',
    useRate: 8.9,
    winRate: 49.2,
    description: 'Splash damage mage. Popular in mid-ladder.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/wizard.png',
  },
  {
    id: 'valkyrie',
    name: 'Valkyrie',
    type: 'troop',
    rarity: 'rare',
    elixir: 4,
    tier: 'B',
    useRate: 11.3,
    winRate: 50.1,
    description: '360 degree splash damage. Good vs swarms and support troops.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/valkyrie.png',
  },
  {
    id: 'inferno-tower',
    name: 'Inferno Tower',
    type: 'building',
    rarity: 'rare',
    elixir: 5,
    tier: 'B',
    useRate: 6.8,
    winRate: 50.7,
    description: 'Ramping damage building. Melts tanks if not reset.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/inferno-tower.png',
  },
  {
    id: 'mega-knight',
    name: 'Mega Knight',
    type: 'troop',
    rarity: 'legendary',
    elixir: 7,
    tier: 'B',
    useRate: 14.2,
    winRate: 48.5,
    description: 'Jump attack splash damage. Popular in mid-ladder but countered easily at high levels.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/mega-knight.png',
  },
  {
    id: 'arrows',
    name: 'Arrows',
    type: 'spell',
    rarity: 'common',
    elixir: 3,
    tier: 'B',
    useRate: 10.5,
    winRate: 49.8,
    description: 'Wide area light damage spell. Great vs Minion Horde.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/arrows.png',
  },
  {
    id: 'tesla',
    name: 'Tesla',
    type: 'building',
    rarity: 'common',
    elixir: 4,
    tier: 'B',
    useRate: 7.4,
    winRate: 50.3,
    description: 'Hidden defensive building. Hits air and ground.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/tesla.png',
  },
  {
    id: 'balloon',
    name: 'Balloon',
    type: 'troop',
    rarity: 'epic',
    elixir: 5,
    tier: 'B',
    useRate: 6.1,
    winRate: 51.4,
    description: 'Flying building-targeting bomb dropper. Devastating if it connects.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/balloon.png',
  },

  // C Tier Cards
  {
    id: 'witch',
    name: 'Witch',
    type: 'troop',
    rarity: 'epic',
    elixir: 5,
    tier: 'C',
    useRate: 5.2,
    winRate: 47.8,
    description: 'Spawns skeletons and deals splash. Inconsistent but fun.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/witch.png',
  },
  {
    id: 'prince',
    name: 'Prince',
    type: 'troop',
    rarity: 'epic',
    elixir: 5,
    tier: 'C',
    useRate: 4.8,
    winRate: 48.2,
    description: 'Charges for double damage. Stopped easily by cheap cards.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/prince.png',
  },
  {
    id: 'sparky',
    name: 'Sparky',
    type: 'troop',
    rarity: 'legendary',
    elixir: 6,
    tier: 'C',
    useRate: 4.1,
    winRate: 49.1,
    description: 'Massive damage but slow charge. Easily reset and countered.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/sparky.png',
  },
  {
    id: 'rage',
    name: 'Rage',
    type: 'spell',
    rarity: 'epic',
    elixir: 2,
    tier: 'C',
    useRate: 3.9,
    winRate: 46.5,
    description: 'Speed boost spell. Very situational and often negative elixir trade.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/rage.png',
  },
  {
    id: 'bomber',
    name: 'Bomber',
    type: 'troop',
    rarity: 'common',
    elixir: 2,
    tier: 'C',
    useRate: 3.4,
    winRate: 47.2,
    description: 'Cheap splash damage. Dies to any spell.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/bomber.png',
  },

  // D Tier Cards
  {
    id: 'heal-spirit',
    name: 'Heal Spirit',
    type: 'troop',
    rarity: 'rare',
    elixir: 1,
    tier: 'D',
    useRate: 2.1,
    winRate: 45.3,
    description: 'Healing troop that jumps. Very niche usage.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/heal-spirit.png',
  },
  {
    id: 'barbarian-hut',
    name: 'Barbarian Hut',
    type: 'building',
    rarity: 'rare',
    elixir: 7,
    tier: 'D',
    useRate: 1.8,
    winRate: 44.1,
    description: 'Spawner building. Too expensive for current meta.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/barbarian-hut.png',
  },
  {
    id: 'mirror',
    name: 'Mirror',
    type: 'spell',
    rarity: 'epic',
    elixir: 0,
    tier: 'D',
    useRate: 2.5,
    winRate: 43.8,
    description: 'Copies last card played at +1 elixir. Very inconsistent.',
    image: 'https://cdn.royaleapi.com/static/img/cards-150/mirror.png',
  },
];

// Meta Decks
export const META_DECKS = [
  {
    id: 'hog-cycle',
    name: '2.6 Hog Cycle',
    cards: ['hog-rider', 'musketeer', 'cannon', 'fireball', 'log', 'skeletons', 'ice-spirit', 'ice-golem'],
    avgElixir: 2.6,
    difficulty: 'Hard',
    archetype: 'Cycle',
    description: 'Classic fast cycle deck. Requires precise micro and elixir management.',
    winRate: 52.8,
  },
  {
    id: 'log-bait',
    name: 'Classic Log Bait',
    cards: ['goblin-barrel', 'princess', 'goblin-gang', 'knight', 'inferno-tower', 'rocket', 'log', 'ice-spirit'],
    avgElixir: 3.0,
    difficulty: 'Medium',
    archetype: 'Bait',
    description: 'Bait out their small spell then punish with Goblin Barrel.',
    winRate: 53.2,
  },
  {
    id: 'golem-beatdown',
    name: 'Golem Beatdown',
    cards: ['golem', 'baby-dragon', 'mega-minion', 'night-witch', 'lightning', 'tornado', 'barb-barrel', 'lumberjack'],
    avgElixir: 4.1,
    difficulty: 'Medium',
    archetype: 'Beatdown',
    description: 'Build massive pushes behind Golem. Sacrifice tower HP early.',
    winRate: 51.5,
  },
  {
    id: 'pekka-bridge-spam',
    name: 'PEKKA Bridge Spam',
    cards: ['pekka', 'battle-ram', 'bandit', 'electro-wizard', 'royal-ghost', 'poison', 'zap', 'minions'],
    avgElixir: 3.6,
    difficulty: 'Medium',
    archetype: 'Bridge Spam',
    description: 'Defend with PEKKA then counter-push with Bridge Spam cards.',
    winRate: 52.1,
  },
  {
    id: 'lavaloon',
    name: 'LavaLoon',
    cards: ['lava-hound', 'balloon', 'mega-minion', 'skeleton-dragons', 'tombstone', 'fireball', 'zap', 'miner'],
    avgElixir: 3.6,
    difficulty: 'Medium',
    archetype: 'Beatdown',
    description: 'Air-based beatdown. Lava Hound tanks for Balloon.',
    winRate: 51.8,
  },
  {
    id: 'xbow-cycle',
    name: 'X-Bow Cycle',
    cards: ['xbow', 'tesla', 'archers', 'knight', 'fireball', 'log', 'skeletons', 'ice-spirit'],
    avgElixir: 2.9,
    difficulty: 'Very Hard',
    archetype: 'Siege',
    description: 'Defensive X-Bow placement. Very matchup dependent.',
    winRate: 50.2,
  },
];

// Helper Functions
export function getCardById(id) {
  return CARDS.find(card => card.id === id);
}

export function getCardsByTier(tier) {
  return CARDS.filter(card => card.tier === tier);
}

export function getCardsByType(type) {
  return CARDS.filter(card => card.type === type);
}

export function getCardsByRarity(rarity) {
  return CARDS.filter(card => card.rarity === rarity);
}

export function getTopCards(count = 10) {
  return [...CARDS]
    .sort((a, b) => b.winRate - a.winRate)
    .slice(0, count);
}

export function getDeckById(id) {
  return META_DECKS.find(deck => deck.id === id);
}

export function getDeckCards(deck) {
  return deck.cards.map(cardId => getCardById(cardId)).filter(Boolean);
}

export default {
  CARDS,
  RARITIES,
  CARD_TYPES,
  TIERS,
  ARENAS,
  META_DECKS,
  getCardById,
  getCardsByTier,
  getCardsByType,
  getCardsByRarity,
  getTopCards,
  getDeckById,
  getDeckCards,
};
